# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\ci\containers\00000vnjfq1\tmp\build\80754af9\rsync-recipes\pyjwt-2.4.0-python_3.8-on-winbuilder, last modified Mon Jul 11 03:39:13 2022
# ------------------------------------------------

package:
  name: pyjwt
  version: 2.4.0
source:
  fn: PyJWT-2.4.0.tar.gz
  sha256: d42908208c699b3b973cbeb01a969ba6a96c821eefb1c5bfe4c390c01d67abba
  url: https://pypi.org/packages/source/P/PyJWT/PyJWT-2.4.0.tar.gz
build:
  number: '0'
  script: C:\\ci\\pyjwt_1657529430378\\_h_env\\python.exe -m pip install . --no-deps
    --ignore-installed -vvv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2022.6.15 py38haa95532_0
    - openssl 1.1.1p h2bbff1b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.13 h6244533_0
    - setuptools 61.2.0 py38haa95532_0
    - sqlite 3.38.5 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
  run_constrained:
    - cryptography >=3.3.1
test:
  commands:
    - pip check
  imports:
    - jwt
  requires:
    - pip
about:
  dev_url: https://github.com/jpadilla/pyjwt
  doc_url: https://pyjwt.readthedocs.io/en/latest/
  home: https://github.com/jpadilla/pyjwt
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: JSON Web Token implementation in Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
