# This file created by conda-build 3.21.7
# meta.yaml template originally from:
# /feedstock/recipe, last modified Tue Mar  8 10:39:30 2022
# ------------------------------------------------

package:
  name: google-auth
  version: 2.6.0
source:
  fn: google-auth-2.6.0.tar.gz
  sha256: ad160fc1ea8f19e331a16a14a79f3d643d813a69534ba9611d2c80dc10439dad
  url: https://pypi.io/packages/source/g/google-auth/google-auth-2.6.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /opt/conda/conda-bld/google-auth_1646735974934/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_p/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 4.5 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2022.2.1 h06a4308_0
    - certifi 2021.5.30 py310h06a4308_0
    - ld_impl_linux-64 2.35.1 h7274673_9
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.3.0 h5101ec6_17
    - libgomp 9.3.0 h5101ec6_17
    - libstdcxx-ng 9.3.0 hd4cf53a_17
    - libuuid 1.0.3 h7f8727e_2
    - ncurses 6.3 h7f8727e_2
    - openssl 1.1.1m h7f8727e_0
    - pip 21.2.4 py310h06a4308_0
    - python 3.10.0 h12debd9_5
    - readline 8.1.2 h7f8727e_1
    - setuptools 58.0.4 py310h06a4308_0
    - sqlite 3.37.2 hc218d9a_0
    - tk 8.6.11 h1ccaba5_0
    - tzdata 2021e hda174b7_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7f8727e_4
  run:
    - aiohttp >=3.6.2,<4.0.0dev
    - cachetools >=2.0.0,<6.0
    - pyasn1-modules >=0.2.1
    - pyopenssl >=20.0.0
    - python >=3.6
    - requests >=2.20.0,<3.0.0dev
    - rsa >=3.1.4,<5
    - setuptools >=40.3.0
    - six >=1.9.0
test:
  commands:
    - python -m pip check
  downstreams:
    - google-cloud-storage
  imports:
    - google.auth
  requires:
    - pip
about:
  description: This library provides the ability to authenticate to Google APIs using
    various methods. It also provides integration with several HTTP libraries.
  dev_url: https://github.com/googleapis/google-auth-library-python
  doc_url: https://google-auth.readthedocs.io/en/latest/
  home: https://github.com/googleapis/google-auth-library-python
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Google authentication library for Python
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - jreback
    - leahecole
    - parthea
    - theacodes
    - tswast
