# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\Users\builder\stiwari\aggregate\tensorflow_recipes\tensorflow-base-cpu-gpu-linwin, last modified Mon Dec  5 10:50:17 2022
# ------------------------------------------------

package:
  name: tensorflow-base
  version: 2.10.0
source:
  fn: tensorflow-2.10.0.tar.gz
  patches: null
  sha256: b5a1bb04c84b6fe1538377e5a1f649bb5d5f0b2e3625a3c526ff3a8af88633e8
  url: https://github.com/tensorflow/tensorflow/archive/v2.10.0.tar.gz
build:
  entry_points:
    - estimator_ckpt_converter = tensorflow_estimator.python.estimator.tools.checkpoint_converter:main
    - saved_model_cli = tensorflow.python.tools.saved_model_cli:main
    - tf_upgrade_v2 = tensorflow.tools.compatibility.tf_upgrade_v2_main:main
    - tflite_convert = tensorflow.lite.python.tflite_convert:main
    - toco = tensorflow.lite.python.tflite_convert:main
    - toco_from_protos = tensorflow.lite.toco.python.toco_from_protos:main
  number: '0'
  string: mkl_py38h6a7f48e_0
requirements:
  build:
    - aws-c-common 0.4.57 ha925a31_1
    - aws-c-event-stream 0.1.6 hd77b12b_5
    - aws-checksums 0.1.9 ha925a31_0
    - aws-sdk-cpp 1.8.185 hd77b12b_0
    - bazel 5.2.0 hd77b12b_0
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py310haa95532_0
    - cython 0.29.32 py310hd77b12b_0
    - git 2.34.1 haa95532_0
    - grpc-cpp 1.46.1 h9c8433d_0
    - libcurl 7.86.0 h86230a5_0
    - libffi 3.4.2 hd77b12b_6
    - libprotobuf 3.20.1 h23ce68f_0
    - libssh2 1.10.0 hcd4344a_0
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-patch 2.7.5 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - nasm 2.13.03 h62dcd97_1
    - openjdk 11.0.13 h2bbff1b_0
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.2.2 py310haa95532_0
    - posix 1.0.0 2
    - python 3.10.8 h966fe2a_1
    - re2 2022.04.01 hd77b12b_0
    - setuptools 65.5.0 py310haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022f h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2019_win-64 19.27.29111 ha89c4d3_2
    - vswhere 2.8.4 haa95532_0
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py310haa95532_2
    - xz 5.2.8 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
  host:
    - absl-py 1.3.0 py38haa95532_0
    - astor 0.8.1 py38haa95532_0
    - astunparse 1.6.3 py_0
    - bazel 5.2.0 hd77b12b_0
    - blas 1.0 mkl
    - brotlipy 0.7.0 py38h2bbff1b_1003
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - cffi 1.15.1 py38h2bbff1b_2
    - charset-normalizer 2.0.4 pyhd3eb1b0_0
    - cryptography 38.0.1 py38h21b164f_0
    - curl 7.86.0 h2bbff1b_0
    - dill 0.3.6 py38haa95532_0
    - fftw 3.3.9 h2bbff1b_1
    - flatbuffers 2.0.0 h6c2663c_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - gast 0.4.0 pyhd3eb1b0_0
    - giflib 5.2.1 h62dcd97_0
    - google-pasta 0.2.0 pyhd3eb1b0_0
    - grpc-cpp 1.46.1 h9c8433d_0
    - grpcio 1.42.0 py38hc60d5dd_0
    - h5py 3.7.0 py38h3de5c98_0
    - hdf5 1.10.6 h1756f20_1
    - icc_rt 2022.1.0 h6049295_2
    - icu 58.2 ha925a31_3
    - idna 3.4 py38haa95532_0
    - intel-openmp 2021.4.0 haa95532_3556
    - jpeg 9e h2bbff1b_0
    - libcurl 7.86.0 h86230a5_0
    - libffi 3.4.2 hd77b12b_6
    - libpng 1.6.37 h2a8f88b_0
    - libprotobuf 3.20.1 h23ce68f_0
    - libssh2 1.10.0 hcd4344a_0
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-db 5.3.28 3
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gdbm 1.11 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libdb 5.3.28 3
    - m2-libgdbm 1.11 4
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-patch 2.7.5 2
    - m2-perl 5.22.1 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - mkl 2021.4.0 haa95532_640
    - mkl-service 2.4.0 py38h2bbff1b_0
    - mkl_fft 1.3.1 py38h277e83a_0
    - mkl_random 1.2.2 py38hf11a4ad_0
    - msys2-conda-epoch 20160418 1
    - nsync 1.24.0 h6c2663c_0
    - numpy 1.20.3 py38ha4e8547_0
    - numpy-base 1.20.3 py38hc2deb75_0
    - openjdk 11.0.13 h2bbff1b_0
    - openssl 1.1.1s h2bbff1b_0
    - opt_einsum 3.3.0 pyhd3eb1b0_1
    - packaging 21.3 pyhd3eb1b0_0
    - pip 22.2.2 py38haa95532_0
    - posix 1.0.0 2
    - protobuf 3.20.1 py38hd77b12b_0
    - pybind11 2.10.1 py38h59b6b97_0
    - pybind11-global 2.10.1 py38h59b6b97_0
    - pycparser 2.21 pyhd3eb1b0_0
    - pyopenssl 22.0.0 pyhd3eb1b0_0
    - pyparsing 3.0.9 py38haa95532_0
    - pysocks 1.7.1 py38haa95532_0
    - python 3.8.15 h6244533_2
    - python-flatbuffers 2.0 pyhd3eb1b0_0
    - re2 2022.04.01 hd77b12b_0
    - requests 2.28.1 py38haa95532_0
    - scipy 1.7.3 py38h7a0a035_2
    - setuptools 65.5.0 py38haa95532_0
    - six 1.16.0 pyhd3eb1b0_1
    - snappy 1.1.9 h6c2663c_0
    - sqlite 3.40.0 h2bbff1b_0
    - swig 4.0.2 hd77b12b_4
    - termcolor 2.1.0 py38haa95532_0
    - typing_extensions 4.4.0 py38haa95532_0
    - urllib3 1.26.12 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - win_inet_pton 1.1.0 py38haa95532_0
    - wincertstore 0.2 py38haa95532_2
    - wrapt 1.14.1 py38h2bbff1b_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - absl-py >=1.0.0
    - astunparse >=1.6.3
    - flatbuffers >=2.0
    - gast 0.4.0.*
    - giflib >=5.2.1,<5.3.0a0
    - google-pasta >=0.1.1
    - grpcio >=1.24.3,<2.0
    - h5py >=2.9.0
    - icu >=58.2,<59.0a0
    - jpeg >=9e,<10a
    - keras 2.10.*
    - libcurl >=7.86.0,<8.0a0
    - libpng >=1.6.37,<1.7.0a0
    - libprotobuf >=3.20.1,<3.21.0a0
    - numpy >=1.20,<2
    - openssl >=1.1.1s,<1.1.2a
    - opt_einsum >=2.3.2
    - packaging
    - python >=3.8,<3.9.0a0
    - python-flatbuffers >=2.0
    - requests
    - scipy >=1.7.3,<2
    - setuptools
    - six >=1.12.0
    - snappy >=1.1.9,<2.0a0
    - sqlite >=3.40.0,<4.0a0
    - tensorboard 2.10.*
    - tensorflow-estimator 2.10.*
    - termcolor >=1.1.0
    - typing_extensions >=3.6.6
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.27.29016,<15.0a0
    - wrapt >=1.11.2
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - saved_model_cli --help
    - tf_upgrade_v2 --help
  imports:
    - tensorflow
about:
  description: 'TensorFlow provides multiple APIs.The lowest level API, TensorFlow
    Core

    provides you with complete programming control.

    Base package contains only tensorflow, not tensorflow-tensorboard.

    '
  dev_url: https://github.com/tensorflow/tensorflow
  doc_source_url: https://github.com/tensorflow/docs/
  doc_url: https://www.tensorflow.org/api_docs
  home: https://tensorflow.org/
  license: Apache-2.0
  license_family: Apache
  summary: TensorFlow is a machine learning library, base package contains only tensorflow.
extra:
  copy_test_source_files: true
  final: true
  tflow_variant: mkl
