# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_fd106csod8\clone\recipe, last modified Fri Mar  3 13:12:07 2023
# ------------------------------------------------

package:
  name: jpeg
  version: 9e
source:
  patches:
    - CMakeLists.txt.patch
  sha256: 4077d6a6a75aeb01884f708919d25934c93305e49f7e3f36db9129320e6f4f3d
  url: https://www.ijg.org/files/jpegsrc.v9e.tar.gz
build:
  number: '1'
  run_exports:
    - jpeg >=9e,<10a
  string: h2bbff1b_1
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - djpeg -dct int -ppm -outfile testout.ppm testorig.jpg
    - if not exist %PREFIX%/Library/lib/pkgconfig/libjpeg.pc exit 1
  files:
    - testorig.jpg
about:
  description: 'This software library is the basis for the processing of images in
    the

    ubiquitous JPEG format and is used worldwide in a countless number of

    applications of software vendors and in the photographic industry under

    a fee-free license with open source code.

    '
  dev_url: https://www.ijg.org/files/
  doc_url: https://www.ijg.org/files/
  home: https://www.ijg.org/
  license: IJG
  license_family: Other
  license_file: README
  summary: read/write jpeg COM, EXIF, IPTC medata
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: fd95eaf0-5a33-4d8c-b061-d04ad2f6ef09
  recipe-maintainers:
    - gillins
    - jakirkham
    - katietz
    - msarahan
  remote_url: git@github.com:AnacondaRecipes/jpeg-feedstock.git
  sha: 839f64da35a7f71e9da8349d847254b2b7c7e6ac
