# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\Windows\TEMP\abs_ac109f85-a7b3-4b4d-bcfd-52622eceddf0hy332ojo\clone\recipe, last modified Thu Jul  7 06:31:45 2022
# ------------------------------------------------

package:
  name: tomli
  version: 2.0.1
source:
  sha256: de526c12914f0c550d15924c62d72abc48d6fe7364aa87328337a31007fe8a4f
  url: https://pypi.io/packages/source/t/tomli/tomli-2.0.1.tar.gz
build:
  number: '0'
  script: C:\\Windows\\TEMP\\abs_ac109f85-a7b3-4b4d-bcfd-52622eceddf0hy332ojo\\croots\\recipe\\tomli_1657175513137\\_h_env\\python.exe
    -m pip install . -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.4.26 haa95532_0
    - certifi 2022.6.15 py38haa95532_0
    - flit-core 3.3.0 pyhd3eb1b0_0
    - openssl 1.1.1p h2bbff1b_0
    - pip 21.2.2 py38haa95532_0
    - python 3.8.13 h6244533_0
    - setuptools 61.2.0 py38haa95532_0
    - sqlite 3.38.5 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  files:
    - example.toml
  imports:
    - tomli
  requires:
    - pip
about:
  dev_url: https://github.com/hukkin/tomli
  doc_url: https://github.com/hukkin/tomli/blob/master/README.md
  home: https://github.com/hukkin/tomli
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A simple TOML parser
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ac109f85-a7b3-4b4d-bcfd-52622eceddf0
  recipe-maintainers:
    - thewchan
  remote_url: git@github.com:AnacondaRecipes/tomli-feedstock.git
  sha: 2bfefbb1d7cc33690713e989b8054a9de751e281
