# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_12_dc77dam\clone\recipe, last modified Mon Sep 11 21:42:19 2023
# ------------------------------------------------

package:
  name: openssl
  version: 1.1.1w
source:
  sha256: cf3098950cb4d853ad95c0841f1f9c6d3dc102dccfcacd521d93925208b76ac8
  url: https://www.openssl.org/source/openssl-1.1.1w.tar.gz
build:
  binary_has_prefix_files: null
  detect_binary_files_with_prefix: true
  number: '0'
  run_exports:
    - openssl >=1.1.1w,<1.1.2a
  string: h2bbff1b_0
requirements:
  build:
    - nasm 2.14.02 h7edc060_0
    - perl 5.26.2.1 h0c8e037_0
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - ca-certificates
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - copy NUL checksum.txt
    - openssl sha256 checksum.txt
    - openssl ecparam -name prime256v1
    - python -c "import certifi; import ssl; import urllib.request as urlrq; urlrq.urlopen('https://pypi.org',
      context=ssl.create_default_context(cafile=certifi.where()))"
  requires:
    - certifi
    - python 3.7.*
    - six
about:
  description: 'OpenSSL is a robust, commercial-grade, full-featured Open Source Toolkit

    for the Transport Layer Security (TLS) protocol formerly known as the

    Secure Sockets Layer (SSL) protocol. The protocol implementation is based

    on a full-strength general purpose cryptographic library, which can also

    be used stand-alone.

    '
  dev_url: https://github.com/openssl/openssl
  doc_url: https://www.openssl.org/docs/man1.1.1/
  home: https://www.openssl.org/
  license: OpenSSL
  license_family: Apache
  license_file: LICENSE
  summary: OpenSSL is an open-source implementation of the SSL and TLS protocols
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1278fd8d-ffa4-4141-9ac5-ba8b46e9ee8b
  recipe-maintainers:
    - carlodri
    - chenghlee
    - jakirkham
    - jjhelmus
    - msarahan
    - ocefpaf
    - pelson
  remote_url: git@github.com:AnacondaRecipes/openssl-feedstock.git
  sha: 8e8a5b1e02d2991311e0807eebc0d277de8d468f
