# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_44ido987fv\clone\recipe, last modified Mon Nov 27 15:09:45 2023
# ------------------------------------------------

package:
  name: multidict
  version: 6.0.4
source:
  patches:
    - patches/0001-Fix-usage-python-C-API-for-version-greater-3.9-and-f.patch
  sha256: 3666906492efb76453c0e7b97f2cf459b0682e7402c0489a95484965dbc1da49
  url: https://pypi.io/packages/source/m/multidict/multidict-6.0.4.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_44ido987fv\\croot\\multidict_1701097803486\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py38h2bbff1b_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - cython 0.29.36 py38h2bbff1b_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3.1 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py38haa95532_0
  run:
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - py.test tests
  imports:
    - multidict
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  description: 'Multidicts are useful for working with HTTP headers, URL query args
    etc.

    '
  dev_url: https://github.com/aio-libs/multidict
  doc_url: https://multidict.aio-libs.org/
  home: https://github.com/aio-libs/multidict
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: The multidict implementation
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 44b0e881-3206-489b-ab5e-b58fbf27fb0d
  recipe-maintainers:
    - kszucs
    - sodre
  remote_url: git@github.com:AnacondaRecipes/multidict-feedstock.git
  sha: ba1959b3a2ad28a75d33bab754f2e0e298129294
