# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\Users\builder\stiwari\aggregate\tensorflow_recipes\keras, last modified Tue Nov 29 16:22:27 2022
# ------------------------------------------------

package:
  name: keras
  version: 2.10.0
source:
  - sha256: 26a6e2c2522e7468ddea22710a99b3290493768fc08a39e75d1173a0e3452fdf
    url: https://pypi.io/packages/py2.py3/k/keras/keras-2.10.0-py2.py3-none-any.whl
  - sha256: 58d1e17ffe5109a7ae296caafcadfdbe6a7d176f0bc4ab01e12a689b0499d8bd
    url: https://raw.githubusercontent.com/keras-team/keras/v2.10.0/LICENSE
build:
  number: '0'
  script:
    - python -m pip install --no-deps --ignore-installed keras-2.10.0-py2.py3-none-any.whl
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.2.2 py38haa95532_0
    - python 3.8.15 h6244533_2
    - setuptools 65.5.0 py38haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - keras-preprocessing >=1.1.2
    - python >=3.8,<3.9.0a0
  run_constrained:
    - tensorflow-base  2.10.*
test:
  commands:
    - pip check
  requires:
    - pip
about:
  description: 'Keras is a minimalist, highly modular neural networks library

    written in Python and capable on running on top of either

    TensorFlow or Theano. It was developed with a focus on enabling

    fast experimentation. Being able to go from idea to result with

    the least possible delay is key to doing good research.

    '
  dev_url: https://github.com/keras-team/keras
  doc_url: https://keras.io
  home: https://github.com/keras-team/keras
  license: Apache-2.0
  license_file: LICENSE
  summary: Deep Learning Library for Theano and TensorFlow
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - croth1
    - ericdill
    - jjhelmus
    - mariusvniekerk
    - ocefpaf
