# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# C:\b\abs_6c28n38aaj\clone\recipe, last modified Wed Aug  2 15:53:14 2023
# ------------------------------------------------

package:
  name: conda-package-streaming
  version: 0.9.0
source:
  sha256: a454def50ab1b69b267c15ef5d97f3b7f492b643694d289d3a9231e8aeaf8943
  url: https://github.com/conda/conda-package-streaming/archive/refs/tags/v0.9.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_6c28n38aaj\\croot\\conda-package-streaming_1690988019210\\_h_env\\python.exe
    -m pip install --no-deps --no-build-isolation . -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2023.05.30 haa95532_0
    - flit-core 3.8.0 py38haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.9 h2bbff1b_0
    - pip 23.2.1 py38haa95532_0
    - python 3.8.17 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - python >=3.8,<3.9.0a0
    - zstandard >=0.15
test:
  commands:
    - pip check
  imports:
    - conda_package_streaming
    - conda_package_streaming.url
  requires:
    - pip
    - requests
about:
  description: 'An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.

    '
  dev_url: https://github.com/conda/conda-package-streaming
  doc_url: https://conda.github.io/conda-package-streaming/
  home: https://github.com/conda/conda-package-streaming
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient library to read from new and old format .conda and .tar.bz2
    conda packages.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6cdc8bce-8986-4478-9563-c905d7815a93
  recipe-maintainers:
    - dholth
  remote_url: git@github.com:AnacondaRecipes/conda-package-streaming-feedstock.git
  sha: 88ae216ed944e3a94500942f9efa6019d5f4ae50
  skip-lints:
    - missing_wheel
