# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Feb 26 19:03:12 2021
# ------------------------------------------------

package:
  name: rsa
  version: 4.7.2
source:
  sha256: 9d689e6ca1b3038bc82bf8d23e944b6b6037bc02301a574935b2dd946e0353b9
  url: https://pypi.io/packages/source/r/rsa/rsa-4.7.2.tar.gz
build:
  entry_points:
    - pyrsa-decrypt = rsa.cli:decrypt
    - pyrsa-encrypt = rsa.cli:encrypt
    - pyrsa-keygen = rsa.cli:keygen
    - pyrsa-priv2pub = rsa.util:private_to_public
    - pyrsa-sign = rsa.cli:sign
    - pyrsa-verify = rsa.cli:verify
  noarch: python
  number: '1'
  script: '/tmp/build/80754af9/rsa_1614366226499/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_/bin/python
    -m pip install . --no-deps --ignore-installed -vv '
  string: pyhd3eb1b0_1
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - ca-certificates 2021.1.19 h06a4308_0
    - certifi 2020.12.5 py36h06a4308_0
    - ld_impl_linux-64 2.33.1 h53a641e_7
    - libedit 3.1.20191231 h14c3975_1
    - libffi 3.3 he6710b0_2
    - libgcc-ng 9.1.0 hdf63c60_0
    - libstdcxx-ng 9.1.0 hdf63c60_0
    - ncurses 6.2 he6710b0_1
    - openssl 1.1.1j h27cfd23_0
    - pip 21.0.1 py36h06a4308_0
    - python 3.6.12 hcff3b4d_2
    - readline 8.1 h27cfd23_0
    - setuptools 52.0.0 py36h06a4308_0
    - sqlite 3.33.0 h62c20be_0
    - tk 8.6.10 hbc83047_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.5 h7b6447c_0
    - zlib 1.2.11 h7b6447c_3
  run:
    - pyasn1 >=0.1.3
    - python
test:
  commands:
    - pip check
    - pyrsa-priv2pub --help
    - pyrsa-keygen --help
    - pyrsa-encrypt --help
    - pyrsa-decrypt --help
    - pyrsa-sign --help
    - pyrsa-verify --help
  imports:
    - rsa
  requires:
    - pip
about:
  home: https://stuvel.eu/rsa
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Pure-Python RSA implementation
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - dbast
    - pmlandwehr
