# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_05b5nut1vk\clone\recipe, last modified Fri Sep 15 12:21:55 2023
# ------------------------------------------------

package:
  name: libwebp-base
  version: 1.3.2
source:
  sha256: 2a499607df669e40258e53d0ade8035ba4ec0175244869d1025d460562aa09b4
  url: https://storage.googleapis.com/downloads.webmproject.org/releases/webp/libwebp-1.3.2.tar.gz
build:
  number: '0'
  run_exports:
    - libwebp-base >=1.3.2,<2.0a0
  string: h2bbff1b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.08.22 haa95532_0
    - cmake 3.26.4 h693b641_0
    - libffi 3.4.4 hd77b12b_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 3.0.10 h2bbff1b_2
    - python 3.11.5 he1021f5_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
  run_constrained:
    - libwebp 1.3.2
test:
  commands:
    - if not exist %LIBRARY_LIB%\libwebp.lib exit 1
    - if not exist %LIBRARY_BIN%\libwebp.dll exit 1
    - if not exist %LIBRARY_PREFIX%\WebP\cmake\WebPConfig.cmake exit 1
    - if not exist %LIBRARY_LIB%\libwebpdemux.lib exit 1
    - if not exist %LIBRARY_BIN%\libwebpdemux.dll exit 1
    - if not exist %LIBRARY_PREFIX%\WebP\cmake\WebPConfig.cmake exit 1
    - if not exist %LIBRARY_LIB%\libwebpmux.lib exit 1
    - if not exist %LIBRARY_BIN%\libwebpmux.dll exit 1
    - if not exist %LIBRARY_PREFIX%\WebP\cmake\WebPConfig.cmake exit 1
    - if not exist %LIBRARY_LIB%\libwebpdecoder.lib exit 1
    - if not exist %LIBRARY_BIN%\libwebpdecoder.dll exit 1
    - if not exist %LIBRARY_PREFIX%\WebP\cmake\WebPConfig.cmake exit 1
    - if not exist %LIBRARY_LIB%\libsharpyuv.lib exit 1
    - if not exist %LIBRARY_BIN%\libsharpyuv.dll exit 1
    - if not exist %LIBRARY_PREFIX%\WebP\cmake\WebPConfig.cmake exit 1
    - if not exist %LIBRARY_INC%\webp\decode.h exit 1
    - if not exist %LIBRARY_INC%\webp\demux.h exit 1
    - if not exist %LIBRARY_INC%\webp\encode.h exit 1
    - if not exist %LIBRARY_INC%\webp\mux_types.h exit 1
    - if not exist %LIBRARY_INC%\webp\mux.h exit 1
    - if not exist %LIBRARY_INC%\webp\types.h exit 1
    - if exist %LIBRARY_BIN%\cwebp.exe exit 1
    - if exist %LIBRARY_BIN%\dwebp.exe exit 1
    - if exist %LIBRARY_BIN%\gif2webp.exe exit 1
    - if exist %LIBRARY_BIN%\img2webp.exe exit 1
    - if exist %LIBRARY_BIN%\webpinfo.exe exit 1
    - if exist %LIBRARY_BIN%\webpmux.exe exit 1
about:
  description: 'WebP is a method of lossy and lossless compression that can be used
    on a

    large variety of photographic, translucent and graphical images found on the

    web. The degree of lossy compression is adjustable so a user can choose the

    trade-off between file size and image quality.

    libwebp-base provides the headers and shared libraries. For cwebp and dwep,

    binaries install libwebp.

    '
  dev_url: https://chromium.googlesource.com/webm/libwebp
  doc_url: https://developers.google.com/speed/webp/docs/using
  home: https://developers.google.com/speed/webp
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: WebP image library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 0571a4f4-51a4-48ab-b2d8-54299c21cf93
  recipe-maintainers:
    - carterbox
    - dschreij
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/libwebp-base-feedstock.git
  sha: 6d1e16f46e8d2a9ac5a6e0aca79f254b78274328
