# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_edevan3fce\clone\recipe, last modified Mon Oct 30 15:26:04 2023
# ------------------------------------------------

package:
  name: sip
  version: 6.7.12
source:
  sha256: 08e66f742592eb818ac8fda4173e2ed64c9f2d40b70bee11db1c499127d98450
  url: https://pypi.io/packages/source/s/sip/sip-6.7.12.tar.gz
build:
  entry_points:
    - sip-build = sipbuild.tools.build:main
    - sip-distinfo = sipbuild.distinfo.main:main
    - sip-install = sipbuild.tools.install:main
    - sip-module = sipbuild.module.main:main
    - sip-sdist = sipbuild.tools.sdist:main
    - sip-wheel = sipbuild.tools.wheel:main
  number: '0'
  run_exports:
    - sip >=6.7.12,<6.8.0a0
  script: C:\\b\\abs_edevan3fce\\croot\\sip_1698675983372\\_h_env\\python.exe -m pip
    install . -vv --no-deps --no-build-isolation
  string: py38hd77b12b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.11 h2bbff1b_2
    - pip 23.3 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py38haa95532_0
  run:
    - packaging
    - ply
    - python >=3.8,<3.9.0a0
    - setuptools
    - tomli
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  files:
    - test
  imports:
    - sipbuild
  requires:
    - pip
    - vs2017_win-64
about:
  description: 'SIP is a collection of tools that makes it very easy to create Python

    bindings for C and C++ libraries. It was originally developed in 1998

    to create PyQt, the Python bindings for the Qt toolkit, but can be

    used to create bindings for any C or C++ library. For example it is

    also used to generate wxPython, the Python bindings for wxWidgets.

    '
  dev_url: https://www.riverbankcomputing.com/software/sip/
  doc_url: https://www.riverbankcomputing.com/software/sip/
  home: https://www.riverbankcomputing.com/software/sip/
  license: LicenseRef-SIP_License OR GPL-2.0-or-later OR GPL-3.0-or-later
  license_family: GPL
  license_file:
    - LICENSE
    - LICENSE-GPL2
    - LICENSE-GPL3
  summary: A Python bindings generator for C/C++ libraries
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: ed10d6a7-f552-42a8-998c-08901a4215e8
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/sip-feedstock.git
  sha: 263e3b8c08c5be15a106c32e3b62585d9ea1f7db
