# This file created by conda-build 3.27.0
# ------------------------------------------------

package:
  name: pyqt
  version: 5.15.10
source:
  - folder: pyqt
    sha256: d46b7804b1b10a4ff91753f8113e5b5580d2b4462f3226288e2d84497334898a
    url: https://pypi.io/packages/source/P/PyQt5/PyQt5-5.15.10.tar.gz
  - folder: pyqt_sip
    sha256: 7f321daf84b9c9dbca61b80e1ef37bdaffc0e93312edae2cd7da25b953971d91
    url: https://pypi.io/packages/source/P/PyQt5-sip/PyQt5_sip-12.13.0.tar.gz
  - folder: pyqt_webengine
    sha256: ae241ef2a61c782939c58b52c2aea53ad99b30f3934c8358d5e0a6ebb3fd0721
    url: https://pypi.io/packages/source/P/PyQtWebEngine/PyQtWebEngine-5.15.6.tar.gz
  - folder: pyqt_charts
    sha256: 2691796fe92a294a617592a5c5c35e785dc91f7759def9eb22da79df63762339
    url: https://pypi.io/packages/source/P/PyQtChart/PyQtChart-5.15.6.tar.gz
build:
  entry_points:
    - pyuic5 = PyQt5.uic.pyuic:main
  missing_dso_whitelist:
    - $RPATH/libc.so.6
    - $RPATH/libm.so.6
    - $RPATH/libpthread.so.0
  number: 0
  run_exports:
    - pyqt >=5.15.10,<5.16.0a0
  string: py38hd77b12b_0
requirements:
  build:
    - glib 2.69.1 h5dc1a3c_2
    - jom 1.1.2 h3bd88b9_0
    - libffi 3.4.4 hd77b12b_0
    - libiconv 1.16 h2bbff1b_2
    - pcre 8.45 hd77b12b_0
    - pkg-config 0.29.2 h8cc25b3_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - zlib 1.2.13 h8cc25b3_0
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - icu 73.1 h6c2663c_0
    - jpeg 9e h2bbff1b_1
    - krb5 1.20.1 h5b6d351_0
    - libclang 14.0.6 default_hb5a9fac_1
    - libclang13 14.0.6 default_h8e68704_1
    - libffi 3.4.4 hd77b12b_0
    - libpng 1.6.39 h8cc25b3_0
    - libpq 12.15 h906ac69_1
    - lz4-c 1.9.4 h2bbff1b_0
    - openssl 3.0.11 h2bbff1b_2
    - packaging 23.1 py38haa95532_0
    - ply 3.11 py38_0
    - pyqt-builder 1.15.3 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - qt-main 5.15.2 h19c9488_10
    - setuptools 68.0.0 py38haa95532_0
    - sip 6.7.12 py38hd77b12b_0
    - sqlite 3.41.2 h2bbff1b_0
    - tomli 2.0.1 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  run:
    - pyqt5-sip 12.13.0 py38h2bbff1b_0
    - python >=3.8,<3.9.0a0
    - qt-main 5.15*
    - qt-main >=5.15.2,<5.16.0a0
    - sip >=6.7.12,<6.8.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  files:
    - pyqt_test.py
  imports:
    - PyQt5
    - PyQt5.QtCore
    - PyQt5.QtGui
    - PyQt5.QtHelp
    - PyQt5.QtMultimedia
    - PyQt5.QtMultimediaWidgets
    - PyQt5.QtNetwork
    - PyQt5.QtOpenGL
    - PyQt5.QtPrintSupport
    - PyQt5.QtQml
    - PyQt5.QtQuick
    - PyQt5.QtSvg
    - PyQt5.QtTest
    - PyQt5.QtWebChannel
    - PyQt5.QtWebSockets
    - PyQt5.QtWidgets
    - PyQt5.QtXml
    - PyQt5.QtXmlPatterns
    - PyQt5.sip
  requires:
    - pip
about:
  description: 'PyQt5 is a comprehensive set of Python bindings for Qt v5.

    It is implemented as more than 35 extension modules and enables Python

    to be used as an alternative application development language to C++ on

    all supported platforms including iOS and Android.

    '
  dev_url: https://www.riverbankcomputing.com/mailman/listinfo/pyqt/
  doc_url: https://www.riverbankcomputing.com/static/Docs/PyQt5/
  home: https://www.riverbankcomputing.com/software/pyqt/
  license: GPL-3.0-only
  license_family: GPL
  license_file: pyqt/LICENSE
  summary: Python bindings for the Qt cross platform application toolkit
extra:
  copy_test_source_files: true
  feedstock-name: pyqt
  final: true
  flow_run_id: c006d7eb-b289-4a7a-9633-4aabe9e0a0b3
  recipe-maintainers:
    - andfoy
    - ccordoba12
    - gillins
    - jschueller
    - katietz
    - mingwandroid
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/pyqt-feedstock.git
  sha: 443f37dcddaf2631bb8152bbb0b88fe74f6aedf9
