# This file created by conda-build 3.28.1
# meta.yaml template originally from:
# C:\b\abs_32c57mq4kh\clone\recipe, last modified Mon Dec 18 14:22:30 2023
# ------------------------------------------------

package:
  name: snappy
  version: 1.1.10
source:
  - patches:
      - 0001-Omit-Werror-during-compilation.patch
      - 0002-Debundle-gtest-and-gmock.patch
      - fix_win_exports.patch
    sha256: 49d831bffcc5f3d01482340fe5af59852ca2fe76c3e05df0e67203ebbe0f1d90
    url: https://github.com/google/snappy/archive/1.1.10.tar.gz
build:
  ignore_run_exports:
    - gtest
  number: '1'
  run_exports:
    - snappy >=1.1.10,<2.0a0
  string: h6c2663c_1
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.26.4 h693b641_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.5 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - gtest 1.14.0 h59b6b97_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %LIBRARY_INC%\snappy.h exit 1
    - if not exist %LIBRARY_INC%\snappy-stubs-public.h exit 1
    - if not exist %LIBRARY_LIB%\snappy.lib exit 1
    - if not exist %LIBRARY_BIN%\snappy.dll exit 1
    - if not exist %LIBRARY_LIB%\snappy_static.lib exit 1
about:
  description: 'Snappy is a compression/decompression library. It does not aim for
    maximum

    compression, or compatibility with any other compression library; instead, it

    aims for very high speeds and reasonable compression. For instance, compared to

    the fastest mode of zlib, Snappy is an order of magnitude faster for most

    inputs, but the resulting compressed files are anywhere from 20% to 100%

    bigger.

    '
  dev_url: https://github.com/google/snappy
  doc_url: https://github.com/google/snappy/tree/master/docs
  home: https://github.com/google/snappy
  license: BSD-3-clause AND CC-BY-3.0 AND MIT AND CC-BY AND Public Domain
  license_family: BSD
  license_file: COPYING
  summary: A fast compressor/decompressor
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 321694fd-9084-443d-8f16-ba2de449d81f
  recipe-maintainers:
    - MaxRis
    - dougalsutherland
    - groutr
    - jakirkham
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/snappy-feedstock.git
  sha: 67d458c9846d8231576bf37b926b8897f0693f8b
