# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: tbb
  version: 2021.8.0
source:
  sha256: eee380323bb7ce864355ed9431f85c43955faaae9e9bce35c62b372d7ffd9f8b
  url: https://github.com/oneapi-src/oneTBB/archive/v2021.8.0.tar.gz
build:
  missing_dso_whitelist: null
  number: 0
  script:
    - set CMAKE_GENERATOR=Ninja
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=%LIBRARY_PREFIX% -DPython3_EXECUTABLE=%PYTHON%
      -DPYTHON_EXECUTABLE=%PYTHON% -DTBB_TEST=OFF -S . -B build
    - cmake --build build --parallel
    - cmake -DCOMPONENT=runtime -P build/cmake_install.cmake
  string: h59b6b97_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_6
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1t h2bbff1b_0
    - python 3.11.2 h966fe2a_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.4 hd43e919_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - python -c "import ctypes, os; os.add_dll_directory(os.environ['LIBRARY_BIN']);
      assert 12080 == ctypes.cdll[r'tbb12.dll'] ['TBB_runtime_interface_version']()"
  requires:
    - python
about:
  description: 'oneTBB is a flexible C++ library that simplifies the work of adding
    parallelism to complex applications, even if you

    are not a threading expert.

    '
  dev_url: https://github.com/oneapi-src/oneTBB
  doc_url: https://oneapi-src.github.io/oneTBB/
  home: https://github.com/oneapi-src/oneTBB
  license: Apache-2.0
  license_family: Apache
  license_file:
    - LICENSE.txt
    - third-party-programs.txt
  summary: High level abstract threading library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 6a172367-0045-4415-a215-23e92203edde
  recipe-maintainers:
    - AlexVeprev
    - anton-malakhov
    - jschueller
  remote_url: git@github.com:AnacondaRecipes/tbb-feedstock.git
  sha: cb408eec4d907f95a745160f914d99435585809d
