# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_19q3ljkez4\clone\recipe, last modified Tue Sep 19 14:53:44 2023
# ------------------------------------------------

package:
  name: pytz
  version: 2023.3.post1
source:
  sha256: 7b4fddbeb94a1eba4b557da24f19fdf9db575192544270a9101d8509f9f43d7b
  url: https://pypi.io/packages/source/p/pytz/pytz-2023.3.post1.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_19q3ljkez4\\croot\\pytz_1695131651401\\_h_env\\python.exe -m
    pip install --no-deps --no-build-isolation . -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.10 h2bbff1b_2
    - pip 23.2.1 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  imports:
    - pytz
  requires:
    - pip
about:
  description: 'pytz brings the Olson tz database into Python. This library allows

    accurate and cross platform timezone calculations using Python 2.4 or

    higher. It also solves the issue of ambiguous times at the end of daylight

    saving time.

    '
  dev_url: https://github.com/stub42/pytz
  doc_url: https://pythonhosted.org/pytz/
  home: https://pythonhosted.org/pytz/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: World timezone definitions, modern and historical.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 19ccb6a8-6a45-421b-b3dd-baafd9f0a196
  recipe-maintainers:
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/pytz-feedstock.git
  sha: 74f9573aa3bd54a1cade33981d6cd547442be054
