# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\000018231pe\tmp\build\80754af9\rsync-recipes\abseil-cpp-20211102.0-on-winbuilder, last modified Fri May 13 02:11:53 2022
# ------------------------------------------------

package:
  name: abseil-cpp
  version: '20211102.0'
source:
  patches:
    - remove-4221.patch
  sha256: dcf71b9cba8dc0ca9940c4b316a0c796be8fab42b070bb6b7cab62b48f0e66c4
  url: https://github.com/abseil/abseil-cpp/archive/20211102.0.tar.gz
build:
  number: '0'
  run_exports:
    - abseil-cpp >=20211102.0,<20211102.1.0a0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.4.26 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 h604cdb4_1
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1o h2bbff1b_0
    - python 3.10.4 hbb2ffb3_0
    - sqlite 3.38.3 h2bbff1b_0
    - tk 8.6.11 h2bbff1b_1
    - tzdata 2022a hda174b7_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands: null
about:
  description: 'Abseil is an open-source collection of C++ code (compliant to C++11)

    designed to augment the C++ standard library.

    '
  dev_url: https://github.com/abseil/abseil-cpp
  doc_url: https://github.com/abseil/abseil-cpp
  home: https://github.com/abseil/abseil-cpp
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Abseil Common Libraries (C++)
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - bluescarni
    - njzjz
    - xhochy
