# This file created by conda-build 3.26.1
# ------------------------------------------------

package:
  name: python
  version: 3.8.18
source:
  - patches:
      - patches/0001-Fix-off-by-one-error-in-_winapi_WaitForMultipleObjec.patch
      - patches/0002-Add-Anaconda-Distribution-version-logic.patch
      - patches/0003-Darwin-Add-arch-x86_64-to-UnicCCompiler-ld_args.patch
      - patches/0004-Win32-Change-FD_SETSIZE-from-512-to-2048.patch
      - patches/0005-Win32-distutils-Add-support-to-cygwinccompiler-for-V.patch
      - patches/0006-Do-not-pass-g-to-GCC-when-not-Py_DEBUG.patch
      - patches/0007-Support-cross-compiling-byte-code.patch
      - patches/0008-Win32-Fixes-for-Windows-GCC-interop-needed-by-RPy2-a.patch
      - patches/0009-Darwin-Look-in-sysroot-usr-lib-include-if-sysroot-is.patch
      - patches/0010-runtime_library_dir_option-Use-1st-word-of-CC-as-com.patch
      - patches/0011-Win32-Do-not-download-externals.patch
      - patches/0012-Add-support-for-_CONDA_PYTHON_SYSCONFIGDATA_NAME-if-.patch
      - patches/0013-Add-CondaEcosystemModifyDllSearchPath.patch
      - patches/0013-Fix-find_library-so-that-it-looks-in-sys.prefix-lib-.patch
      - patches/0014-Disable-new-dtags-in-unixccompiler.py.patch
      - patches/0015-Fix-cross-compilation-on-Debian-based-distros.patch
      - patches/0016-Disable-registry-lookup-unless-CONDA_PY_ALLOW_REG_PA.patch
      - patches/0017-Unvendor-openssl.patch
      - patches/0018-Unvendor-sqlite3.patch
      - patches/0019-venv-Revert-a-change-from-https-github.com-python-cp.patch
      - patches/0020-Win-Add-back-the-DLLSuffix-used-to-find-the-openssl-.patch
      - patches/0021-Use-ranlib-from-env-if-env-variable-is-set.patch
      - patches/0024-cross-compile-darwin.patch.patch
      - patches/0032-ctypes-link-to-coreFoundation.patch
      - patches/0034-Use-OpenSSL-3-instead-of-1_1.patch
    sha256: 3ffb71cd349a326ba7b2fadc7e7df86ba577dd9c4917e52a8401adbda7405e3f
    url: https://www.python.org/ftp/python/3.8.18/Python-3.8.18.tar.xz
  - folder: externals/xz-5.2.2
    sha256: 02b6d6f1e0369940e7e1f0d324992e069d09f5f3d32d86e2d22cd8b82ac3fb3f
    url: https://github.com/python/cpython-source-deps/archive/xz-5.2.2.zip
  - folder: externals/tcl-core-8.6.9.0
    sha256: ea9e724536ec13b476ebbd47948303b92fdd90a33aa94f30fcc2f5c3a899f69e
    url: https://github.com/python/cpython-source-deps/archive/tcl-core-8.6.9.0.zip
  - folder: externals/tk-8.6.9.0
    sha256: f3112b6bbc3bd163c877030187e73ce9a113ce03eff559ec5b9df697e3a08fad
    url: https://github.com/python/cpython-source-deps/archive/tk-8.6.9.0.zip
  - folder: externals/tcltk-8.6.9.0
    sha256: 37cd629a75d2a34974a3d771ccab5c9e3caf3d138cea81040f9cdba1aded1cf2
    url: https://github.com/python/cpython-bin-deps/archive/tcltk-8.6.9.0.zip
  - folder: externals/tix-8.4.3.6
    sha256: e558e3dc5e67ac0942f8fceafce00ca46b177da9ebeaf38ec7fafd9b9913ac56
    url: https://github.com/python/cpython-source-deps/archive/tix-8.4.3.6.zip
  - folder: externals/bzip2-1.0.8
    sha256: 12c17d15f99e27235529574a722fb484a4e8fdf2427cef53b1b68bdf07e404a9
    url: https://github.com/python/cpython-source-deps/archive/bzip2-1.0.8.zip
  - folder: externals/zlib-1.2.12
    sha256: 92197502951ac8414ece9f2d9fa2cc010c51d610e6b2ed9833ba4a35d65f222b
    url: https://github.com/python/cpython-source-deps/archive/zlib-1.2.12.zip
  - folder: externals/nasm-2.11.06
    sha256: de3c87b26a80e789986d8e6950c6304175d3829afe9c6c7211eb7257266ab0ac
    url: https://github.com/python/cpython-bin-deps/archive/nasm-2.11.06.zip
  - folder: externals/libffi-3.3.0
    sha256: 69e3f7235108a75033cb9325a0a3535ba271d144ec66fccefe134eda27d7bcfe
    url: https://github.com/python/cpython-bin-deps/archive/libffi-3.3.0.zip
build:
  activate_in_script: true
  detect_binary_files_with_prefix: true
  missing_dso_whitelist:
    - '**/MSVCR71.dll'
    - '**/MSVCR80.dll'
  no_link:
    - DLLs/_ctypes.pyd
  number: 0
  run_exports:
    noarch:
      - python
  string: h1aa4202_0
requirements:
  build:
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - posix 1.0.0 2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - openssl 3.0.10 h2bbff1b_2
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - libffi >=3.4,<3.5
    - openssl >=3.0.10,<4.0a0
    - sqlite >=3.41.2,<4.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - echo on
    - set
    - python -V
    - 2to3 -h
    - pydoc -h
    - set "PIP_NO_BUILD_ISOLATION=False"
    - set "PIP_NO_DEPENDENCIES=True"
    - set "PIP_IGNORE_INSTALLED=True"
    - set "PIP_NO_INDEX=True"
    - set "PIP_CACHE_DIR=%CONDA_PREFIX%/pip_cache"
    - set "TEMP=%CONDA_PREFIX%/tmp"
    - mkdir "%TEMP%"
    - python -Im ensurepip --upgrade --default-pip
    - python -m venv test-venv
    - if exist %PREFIX%\\Scripts\\pydoc exit 1
    - if exist %PREFIX%\\Scripts\\idle exit 1
    - if exist %PREFIX%\\Scripts\\2to3 exit 1
    - if not exist %PREFIX%\\Scripts\\pydoc-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\idle-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\2to3-script.py exit 1
    - if not exist %PREFIX%\\Scripts\\idle.exe exit 1
    - if not exist %PREFIX%\\Scripts\\2to3.exe exit 1
    - if not exist %PREFIX%\\Scripts\\pydoc.exe exit 1
    - pushd tests
    - pushd distutils
    - python setup.py install -v -v
    - python -c "import foobar"
    - popd
    - pushd distutils.cext
    - python setup.py build_ext -v -v
    - echo %cd%
    - dir .
    - dir build
    - pushd build\lib*
    - echo %cd%
    - echo "After pushd build/lib"
    - python -c "import greet; greet.greet('Python user')" | rg "Hello Python"
    - echo "After python -c import"
    - popd
    - popd
    - pushd cmake
    - cmake -GNinja -DPY_VER=3.8.18
    - popd
    - popd
    - python -c "import ssl; assert '3.0' in ssl.OPENSSL_VERSION"
  files:
    - tests/cmake/*
    - tests/cython/*
    - tests/distutils.cext/*
    - tests/distutils/*
    - tests/prefix-replacement/*
  requires:
    - cmake-no-system
    - cython
    - ninja-base
    - ripgrep
    - setuptools
    - vs2017_win-64
about:
  description: 'Python is a widely used high-level, general-purpose, interpreted,
    dynamic

    programming language. Its design philosophy emphasizes code

    readability, and its syntax allows programmers to express concepts in

    fewer lines of code than would be possible in languages such as C++ or

    Java. The language provides constructs intended to enable clear programs

    on both a small and large scale.

    '
  dev_url: https://devguide.python.org/
  doc_url: https://www.python.org/doc/versions/
  home: https://www.python.org/
  license: PSF-2.0
  license_family: PSF
  license_file: LICENSE
  license_url: https://docs.python.org/3.8/license.html
  summary: General purpose programming language
extra:
  copy_test_source_files: true
  feedstock-name: python
  final: true
  flow_run_id: 04d0bd95-5dcd-472f-84b3-add4ef518997
  recipe-maintainers:
    - isuruf
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - pelson
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/python-feedstock.git
  sha: d0e215f8c3560b286988a109a888ac61c34975a7
