# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_daon7wm2p4\clone\recipe, last modified Fri Sep 15 15:36:03 2023
# ------------------------------------------------

package:
  name: scikit-learn
  version: 1.3.0
source:
  sha256: 8be549886f5eda46436b6e555b0e4873b4f10aa21c07df45c4bc1735afbccd7a
  url: https://pypi.io/packages/source/s/scikit-learn/scikit-learn-1.3.0.tar.gz
build:
  missing_dso_whitelist: null
  number: '1'
  script:
    - C:\\b\\abs_daon7wm2p4\\croot\\scikit-learn_1694788586973\\_h_env\\python.exe
      -m pip install --no-deps --ignore-installed --no-build-isolation . -vv
  string: py38h4ed8f06_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - blas 1.0 mkl
    - ca-certificates 2023.08.22 haa95532_0
    - cython 0.29.36 py38h2bbff1b_0
    - icc_rt 2022.1.0 h6049295_2
    - intel-openmp 2023.1.0 h59b6b97_46319
    - libffi 3.4.4 hd77b12b_0
    - mkl 2023.1.0 h6b88ed4_46357
    - mkl-service 2.4.0 py38h2bbff1b_1
    - mkl_fft 1.3.6 py38hf11a4ad_1
    - mkl_random 1.2.2 py38hf11a4ad_1
    - numpy 1.21.5 py38h6917f2d_4
    - numpy-base 1.21.5 py38h46c4fa8_4
    - openssl 3.0.10 h2bbff1b_2
    - pip 23.2.1 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - scipy 1.9.3 py38hdcfc7df_2
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tbb 2021.8.0 h59b6b97_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - joblib >=1.1.1
    - numpy >=1.21.5,<2.0a0
    - python >=3.8,<3.9.0a0
    - scipy >=1.5.0
    - threadpoolctl >=2.0.0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - set OPENBLAS_NUM_THREADS=1
    - set OMP_NUM_THREADS=1
    - pytest --timeout 300 -n 1 --verbose --pyargs sklearn -k "not (_not_a_real_test
      or test_loadings_converges)"
  imports:
    - sklearn
    - sklearn.cluster
    - sklearn.datasets
    - sklearn.decomposition
    - sklearn.ensemble
    - sklearn.feature_extraction
    - sklearn.linear_model
    - sklearn.manifold
    - sklearn.metrics
    - sklearn.neighbors
    - sklearn.svm
    - sklearn.tree
    - sklearn.utils
  requires:
    - cython >=0.29.24
    - pip
    - pytest >=7.1.2
    - pytest-timeout
    - pytest-xdist
about:
  description: 'Scikit-learn is an open source machine learning library that supports
    supervised and unsupervised learning.

    It also provides various tools for model fitting, data preprocessing, model selection,
    model evaluation,

    and many other utilities.

    '
  dev_url: https://github.com/scikit-learn/scikit-learn
  doc_url: https://scikit-learn.org/dev/user_guide.html
  home: https://scikit-learn.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: A set of python modules for machine learning and data mining
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: da50aead-d004-48d9-88d9-b28ddf50989e
  recipe-maintainers:
    - adrinjalali
    - amueller
    - astaric
    - glemaitre
    - jakirkham
    - jeremiedbb
    - jnothman
    - lesteve
    - ocefpaf
    - ogrisel
    - rth
  remote_url: git@github.com:AnacondaRecipes/scikit-learn-feedstock.git
  sha: 277e8744a3ce4321db8e624786043aeda39fb767
