# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_707eo7c09t\clone\recipe, last modified Tue Feb 28 23:58:28 2023
# ------------------------------------------------

package:
  name: boltons
  version: 23.0.0
source:
  fn: boltons-23.0.0.tar.gz
  sha256: 9b2998cd9525ed472079c7dd90fbd216a887202e8729d5969d4f33878f0ff668
  url: https://github.com/mahmoud/boltons/archive/23.0.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_707eo7c09t\\croot\\boltons_1677628723117\\_h_env\\python.exe
    -m pip install . --no-deps -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py38haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1t h2bbff1b_0
    - pip 22.3.1 py38haa95532_0
    - python 3.8.16 h6244533_2
    - setuptools 65.6.3 py38haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pytest -vv --doctest-modules boltons tests -k "not test_reverse_iter_lines"
    - pip check
  imports:
    - boltons
    - boltons.cacheutils
    - boltons.debugutils
    - boltons.dictutils
    - boltons.ecoutils
    - boltons.fileutils
    - boltons.formatutils
    - boltons.funcutils
    - boltons.gcutils
    - boltons.ioutils
    - boltons.iterutils
    - boltons.jsonutils
    - boltons.listutils
    - boltons.mathutils
    - boltons.mboxutils
    - boltons.namedutils
    - boltons.pathutils
    - boltons.queueutils
    - boltons.setutils
    - boltons.socketutils
    - boltons.statsutils
    - boltons.strutils
    - boltons.tableutils
    - boltons.tbutils
    - boltons.timeutils
    - boltons.typeutils
    - boltons.urlutils
  requires:
    - pip
    - pytest
  source_files:
    - boltons
    - pytest.ini
    - tests
about:
  description: "Boltons is a set of pure-Python utilities in the same spirit as \u2014\
    \ and yet conspicuously missing from \u2014 the standard library, including:\n\
    \n  - Atomic file saving, bolted on with fileutils\n  - A highly-optimized OrderedMultiDict,\
    \ in dictutils\n  - Two types of PriorityQueue, in queueutils\n  - Chunked and\
    \ windowed iteration, in iterutils\n  - A full-featured TracebackInfo type, for\
    \ representing stack traces, in tbutils\n  - A lightweight UTC timezone available\
    \ in timeutils.\n  - Recursive mapping for nested data transforms, with remap\n"
  dev_url: https://github.com/mahmoud/boltons
  doc_url: https://boltons.readthedocs.io/
  home: https://github.com/mahmoud/boltons
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'boltons should be builtins. Boltons is a set of over 160 BSD-licensed,
    pure-Python utilities in the same spirit as--and yet conspicuously missing from--the
    standard library.

    '
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 70500309-3e66-430a-b9b9-a50adfa4386d
  recipe-maintainers:
    - kalefranz
    - nicoddemus
  remote_url: git@github.com:AnacondaRecipes/boltons-feedstock.git
  sha: 1d419355e50979b5269329d2635120d45ad58b07
