# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\b\abs_2fhvpo862s\clone\recipe, last modified Mon Dec 12 13:59:49 2022
# ------------------------------------------------

package:
  name: tensorboard-data-server
  version: 0.6.1
source:
  patches:
    - 0001-Do-not-try-to-remove-tmpdir-on-Windows.patch
  sha256: 712996fea67cea2a2bcc07debe46bebcecbac7b862f42d760cc3b2ed31f79a5a
  url: https://github.com/tensorflow/tensorboard/archive/6acf0be88b5727e546dd64a8b9b12d790601d561.zip
build:
  number: '0'
  script_env:
    - WHEELNAME=tensorboard_data_server-0.6.1-py3-none-any.whl
  string: py38haa95532_0
requirements:
  build:
    - ca-certificates 2022.10.11 haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - openssl 1.1.1s h2bbff1b_0
    - python 3.8.15 h6244533_2
    - sqlite 3.40.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  host:
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.3.1 py38haa95532_0
    - python 3.8.15 h6244533_2
    - setuptools 65.5.0 py38haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  imports:
    - tensorboard_data_server
  requires:
    - pip
about:
  dev_url: https://github.com/tensorflow/tensorboard/tree/master/tensorboard/data/server
  home: https://github.com/tensorflow/tensorboard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Data server for TensorBoard
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 2f048e36-5047-4553-9037-c8f44142e1af
  recipe-maintainers:
    - mdraw
  remote_url: git@github.com:AnacondaRecipes/tensorboard-data-server-feedstock.git
  sha: dadc13d156063c8927ea5baa3bb8aee84f5b0a64
  skip-lints:
    - missing_description
    - missing_doc_source_url
    - missing_doc_url
    - missing_license_url
