# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_d5rpy288vc\clone\recipe, last modified Thu Sep 22 06:16:50 2022
# ------------------------------------------------

package:
  name: contourpy
  version: 1.0.5
source:
  sha256: 896631cd40222aef3697e4e51177d14c3709fda49d30983269d584f034acc8a4
  url: https://pypi.io/packages/source/c/contourpy/contourpy-1.0.5.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_d5rpy288vc\\croots\\recipe\\contourpy_1663827418189\\_h_env\\python.exe
    -m pip install . -vv
  string: py38h59b6b97_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.9.14 py38haa95532_0
    - openssl 1.1.1q h2bbff1b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pep517 0.12.0 py38haa95532_0
    - pip 22.1.2 py38haa95532_0
    - pybind11 2.9.2 py38h757b272_0
    - pyparsing 3.0.9 py38haa95532_0
    - python 3.8.13 h6244533_0
    - python-build 0.7.0 pyhd3eb1b0_0
    - setuptools 63.4.1 py38haa95532_0
    - sqlite 3.39.2 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 2.0.1 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - numpy >=1.16
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - python -c "import contourpy as c; c.contour_generator(z=[[0, 1], [2, 3]]).lines(0.9)"
  imports:
    - contourpy
    - contourpy.util
  requires:
    - pip
about:
  description: 'ContourPy is a Python library for calculating contours of 2D quadrilateral

    grids.  It is written in C++11 and wrapped using pybind11.

    '
  dev_url: https://github.com/contourpy/contourpy
  doc_sourc_url: https://github.com/contourpy/contourpy/tree/main/docs
  doc_url: https://contourpy.readthedocs.io
  home: https://github.com/contourpy/contourpy
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  license_url: https://github.com/contourpy/contourpy/blob/main/LICENSE
  summary: Python library for calculating contours of 2D quadrilateral grids.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d5b35ade-723e-4c91-b786-57f5cd107753
  recipe-maintainers:
    - ianthomas23
  remote_url: git@github.com:AnacondaRecipes/contourpy-feedstock.git
  sha: c3682854f6d9e0cf66cb39514bc12789fa40a9d9
