# This file created by conda-build 3.28.4
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Feb 19 17:16:52 2024
# ------------------------------------------------

package:
  name: tornado
  version: '6.4'
source:
  sha256: 72291fa6e6bc84e626589f1c29d90a5a6d593ef5ae68052ee2ef000dfd273dee
  url: https://pypi.io/packages/source/t/tornado/tornado-6.4.tar.gz
build:
  number: '0'
  script: D:\\bld\\tornado_1708363253587\\_h_env\\python.exe -m pip install . -vv
    --no-deps --no-build-isolation
  string: py38h91455d4_0
requirements:
  build:
    - vs2019_win-64 19.29.30139 he1865b1_18
    - vswhere 3.1.4 h57928b3_0
  host:
    - bzip2 1.0.8 hcfcfb64_5
    - ca-certificates 2024.2.2 h56e8100_0
    - libffi 3.4.2 h8ffe710_5
    - libsqlite 3.45.1 hcfcfb64_0
    - libzlib 1.2.13 hcfcfb64_5
    - openssl 3.2.1 hcfcfb64_0
    - pip 24.0 pyhd8ed1ab_0
    - python 3.8.18 h4de0772_1_cpython
    - setuptools 69.1.0 pyhd8ed1ab_0
    - tk 8.6.13 h5226925_1
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 hcf57466_18
    - vc14_runtime 14.38.33130 h82b7239_18
    - vs2015_runtime 14.38.33130 hcb4865c_18
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
  run:
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  commands:
    - pip check
  imports:
    - tornado
    - tornado.gen
    - tornado.netutil
    - tornado.platform
    - tornado.test
  requires:
    - pip
about:
  description: 'Tornado is a Python web framework and asynchronous networking library.

    By using non-blocking network I/O, Tornado can scale to tens of thousands

    of open connections, making it ideal for long polling, WebSockets, and

    other applications that require a long-lived connection to each user.

    '
  dev_url: https://github.com/tornadoweb/tornado
  doc_source_url: https://github.com/tornadoweb/tornado/blob/stable/docs/index.rst
  doc_url: https://www.tornadoweb.org/en/stable/
  home: https://www.tornadoweb.org/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  license_url: https://www.apache.org/licenses/LICENSE-2.0
  summary: A Python web framework and asynchronous networking library, originally
    developed at FriendFeed.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240219.1.1
  recipe-maintainers:
    - jakirkham
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/tornado-feedstock
  sha: d1cc7686100b434c3460fabfa84fd43bc2b2a0bc
