# This file created by conda-build 3.18.11
# meta.yaml template originally from:
# /tmp/build/80754af9/rsync-recipes/requests-oauthlib-1.3.0-on-linux_64, last modified Thu Nov 21 20:23:12 2019
# ------------------------------------------------

package:
    name: requests-oauthlib
    version: 1.3.0
source:
    fn: requests-oauthlib-1.3.0.tar.gz
    sha256: b4261601a71fd721a8bd6d7aa1cc1d6a8a93b4a9f5e96626f8e4d91e8beeaa6a
    url: https://pypi.org/packages/source/r/requests-oauthlib/requests-oauthlib-1.3.0.tar.gz
build:
    noarch: python
    number: '0'
    script: python -m pip install --no-deps --ignore-installed .
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - asn1crypto 1.2.0 py27_0
        - blinker 1.4 py27_0
        - ca-certificates 2019.10.16 0
        - certifi 2019.9.11 py27_0
        - cffi 1.13.2 py27h2e261b9_0
        - chardet 3.0.4 py27_1003
        - cryptography 2.8 py27h1ba5d50_0
        - enum34 1.1.6 py27_1
        - idna 2.8 py27_0
        - ipaddress 1.0.23 py_0
        - libedit 3.1.20181209 hc058e9b_0
        - libffi 3.2.1 hd88cf55_4
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.1 he6710b0_1
        - oauthlib 3.1.0 py_0
        - openssl 1.1.1d h7b6447c_3
        - pip 19.3.1 py27_0
        - pycparser 2.19 py27_0
        - pyjwt 1.7.1 py27_0
        - pyopenssl 19.1.0 py27_0
        - pysocks 1.7.1 py27_0
        - python 2.7.17 h9bab390_0
        - readline 7.0 h7b6447c_5
        - requests 2.22.0 py27_0
        - setuptools 41.6.0 py27_0
        - six 1.13.0 py27_0
        - sqlite 3.30.1 h7b6447c_0
        - tk 8.6.8 hbc83047_0
        - urllib3 1.24.2 py27_0
        - wheel 0.33.6 py27_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - oauthlib >=3.0.0
        - python
        - requests >=2.0.0
test:
    imports:
        - requests_oauthlib
        - requests_oauthlib.compliance_fixes
about:
    dev_url: https://github.com/requests/requests-oauthlib
    doc_url: https://github.com/requests/requests-oauthlib
    home: https://github.com/requests/requests-oauthlib
    license: ISC
    license_file: LICENSE
    summary: OAuthlib authentication support for Requests.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pmlandwehr
