# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: grpcio
  version: 1.48.2
source:
  patches:
    - patches/0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch
    - patches/0001-fix-win-commands.patch
    - patches/0002-windows-ssl-lib-names.patch
    - patches/0003-Link-against-grpc.patch
    - patches/force-protoc-executable.patch
  sha256: bdb8e98145469d58c69ab9f2c9e0bd838c2836a99b5760bc0ebf658623768f52
  url: https://github.com/grpc/grpc/archive/v1.48.2.tar.gz
build:
  missing_dso_whitelist: null
  number: 0
  string: py38hf108199_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - abseil-cpp 20211102.0 hd77b12b_0
    - c-ares 1.19.0 h2bbff1b_0
    - ca-certificates 2023.01.10 haa95532_0
    - cython 0.29.33 py38hd77b12b_0
    - grpc-cpp 1.48.2 hf108199_0
    - libffi 3.4.2 hd77b12b_6
    - libprotobuf 3.20.3 h23ce68f_0
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py38haa95532_0
    - python 3.8.16 h6244533_3
    - re2 2022.04.01 hd77b12b_0
    - setuptools 66.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - abseil-cpp >=20211102.0,<20211102.1.0a0
    - c-ares >=1.19.0,<2.0a0
    - grpc-cpp 1.48.2 hf108199_0
    - libprotobuf >=3.20.3,<3.21.0a0
    - openssl >=1.1.1t,<1.1.2a
    - python >=3.8,<3.9.0a0
    - re2 >=2022.4.1,<2022.4.2.0a0
    - six >=1.6.0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - pip check
  imports:
    - grpc
    - grpc._cython
    - grpc._cython._cygrpc
    - grpc.beta
    - grpc.framework
    - grpc.framework.common
    - grpc.framework.foundation
    - grpc.framework.interfaces
    - grpc.framework.interfaces.base
    - grpc.framework.interfaces.face
  requires:
    - pip
about:
  description: 'gRPC is a modern, open source, high-performance remote procedure call

    (RPC) framework that can run anywhere. gRPC enables client and server

    applications to communicate transparently, and simplifies the building

    of connected systems.


    This package contains the gRPC C++ libraries and header files, as well

    as the code generation plugins.

    '
  dev_url: https://github.com/grpc/grpc
  doc_url: https://grpc.io/docs/
  home: https://grpc.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: gRPC - A high-performance, open-source universal RPC framework
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cc800219-7cd0-4f6d-9250-9c011873302c
  recipe-maintainers:
    - mingwandroid
    - pitrou
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/grpc-cpp-feedstock.git
  sha: 8a0c86d8191910d174fa7b84ca2e123c6387e30f
