# This file created by conda-build 3.20.2
# meta.yaml template originally from:
# /tmp/build/80754af9/combined_recipe, last modified Fri Sep 18 16:05:32 2020
# ------------------------------------------------

package:
    name: munkres
    version: 1.1.4
source:
    fn: munkres-1.1.4.tar.gz
    sha256: 6a297282895e4f7c27902bb5ad045d06458905daafb80a9ce14b9d87ca391205
    url: https://github.com/bmc/munkres/archive/release-1.1.4.tar.gz
build:
    noarch: python
    number: '0'
    script: python setup.py install --single-version-externally-managed --record record.txt
    string: py_0
requirements:
    host:
        - _libgcc_mutex 0.1 main
        - ca-certificates 2020.7.22 0
        - certifi 2020.6.20 py36_0
        - ld_impl_linux-64 2.33.1 h53a641e_7
        - libedit 3.1.20191231 h14c3975_1
        - libffi 3.3 he6710b0_2
        - libgcc-ng 9.1.0 hdf63c60_0
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - ncurses 6.2 he6710b0_1
        - openssl 1.1.1g h7b6447c_0
        - python 3.6.12 hcff3b4d_2
        - readline 8.0 h7b6447c_0
        - setuptools 49.6.0 py36_0
        - sqlite 3.33.0 h62c20be_0
        - tk 8.6.10 hbc83047_0
        - xz 5.2.5 h7b6447c_0
        - zlib 1.2.11 h7b6447c_3
    run:
        - python
test:
    commands:
        - py.test
    imports:
        - munkres
    requires:
        - pytest
    source_files:
        - test/*
about:
    description: 'The Munkres module provides an O(n^3) implementation of the Munkres

        algorithm (also called the Hungarian algorithm or the Kuhn-Munkres

        algorithm). The algorithm models an assignment problem as an NxM cost

        matrix, where each element represents the cost of assigning the ith worker

        to the jth job, and it figures out the least-cost solution, choosing a

        single item from each row and column in the matrix, such that no row and

        no column are used more than once.

        '
    dev_url: https://github.com/bmc/munkres
    doc_url: http://software.clapper.org/munkres/
    home: https://github.com/bmc/munkres
    license: Apache-2.0
    license_family: Apache
    license_file: LICENSE.md
    summary: The Munkres module provides an O(n^3) implementation of the Munkres algorithm
        (also called the Hungarian algorithm or the Kuhn-Munkres algorithm).
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - CJ-Wright
