# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_cfdq04jts9\clone\recipe, last modified Tue Feb 21 12:39:25 2023
# ------------------------------------------------

package:
  name: giflib
  version: 5.2.1
source:
  - patches:
      - CVE-2022-28506.patch
      - fix_win.patch
      - stdbool_h.patch
    sha256: 31da5562f44c5f15d63340a09a4fd62b48c45620cd302f77a6d9acf0077879bd
    url: https://downloads.sourceforge.net/project/giflib/giflib-5.2.1.tar.gz
  - path: getopt.h
build:
  number: '3'
  run_exports:
    - giflib >=5.2.1,<5.3.0a0
  string: h8cc25b3_3
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - git 2.34.1 haa95532_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - gifbuild -h
    - giffix -h
    - giftext -h
    - gifclrmp -h
    - gif2rgb -h
about:
  description: 'The GIFLIB project maintains the giflib service library, which has
    been pulling images

    out of GIFs since 1989. It is deployed everywhere you can think of and some places
    you

    probably can''t - graphics applications and web browsers on multiple operating
    systems,

    game consoles, smartphones, and likely your ATM too.

    '
  dev_url: https://giflib.sourceforge.net
  doc_url: https://giflib.sourceforge.net
  home: https://giflib.sourceforge.net
  license: MIT
  license_family: MIT
  license_file:
    - COPYING
    - getopt_LICENSE.txt
  summary: Library for reading and writing gif images
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cff45622-ed2f-4647-9a2a-40df4aad44a8
  recipe-maintainers:
    - 183amir
    - isuruf
    - katietz
    - msarahan
    - ocefpaf
    - wolfv
  remote_url: git@github.com:AnacondaRecipes/giflib-feedstock.git
  sha: 8995916c66c79706414622acd41ebb83892e6068
