# This file created by conda-build 24.1.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Tue Feb 27 01:14:25 2024
# ------------------------------------------------

package:
  name: ipykernel
  version: 6.29.3
source:
  sha256: e14c250d1f9ea3989490225cc1a542781b095a18a19447fcf2b5eaf7d0ac5bd2
  url: https://pypi.io/packages/source/i/ipykernel/ipykernel-6.29.3.tar.gz
build:
  noarch: python
  number: '0'
  script:
    - D:\\bld\\ipykernel_1708996677248\\_h_env\\python.exe -m pip install . -vv --no-deps
      --no-build-isolation
    - D:\\bld\\ipykernel_1708996677248\\_h_env\\python.exe -m ipykernel install --sys-prefix
  script_env:
    - MIGRATING=False
  string: pyha63f2e9_0
requirements:
  host:
    - asttokens 2.4.1 pyhd8ed1ab_0
    - backcall 0.2.0 pyh9f0ad1d_0
    - bzip2 1.0.8 hcfcfb64_5
    - ca-certificates 2024.2.2 h56e8100_0
    - colorama 0.4.6 pyhd8ed1ab_0
    - comm 0.2.1 pyhd8ed1ab_0
    - debugpy 1.8.1 py38hd3f51b4_0
    - decorator 5.1.1 pyhd8ed1ab_0
    - editables 0.5 pyhd8ed1ab_0
    - executing 2.0.1 pyhd8ed1ab_0
    - hatchling 1.21.1 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - importlib_metadata 7.0.1 hd8ed1ab_0
    - ipython 8.12.2 pyh08f2357_0
    - jedi 0.19.1 pyhd8ed1ab_0
    - jupyter_client 8.6.0 pyhd8ed1ab_0
    - jupyter_core 5.7.1 py38haa244fe_0
    - libffi 3.4.2 h8ffe710_5
    - libsodium 1.0.18 h8d14728_1
    - libsqlite 3.45.1 hcfcfb64_0
    - libzlib 1.2.13 hcfcfb64_5
    - matplotlib-inline 0.1.6 pyhd8ed1ab_0
    - openssl 3.2.1 hcfcfb64_0
    - packaging 23.2 pyhd8ed1ab_0
    - parso 0.8.3 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pickleshare 0.7.5 py_1003
    - pip 24.0 pyhd8ed1ab_0
    - platformdirs 4.2.0 pyhd8ed1ab_0
    - pluggy 1.4.0 pyhd8ed1ab_0
    - prompt-toolkit 3.0.42 pyha770c72_0
    - prompt_toolkit 3.0.42 hd8ed1ab_0
    - psutil 5.9.8 py38h91455d4_0
    - pure_eval 0.2.2 pyhd8ed1ab_0
    - pygments 2.17.2 pyhd8ed1ab_0
    - python 3.8.18 h4de0772_1_cpython
    - python-dateutil 2.8.2 pyhd8ed1ab_0
    - python_abi 3.8 4_cp38
    - pywin32 306 py38hd3f51b4_2
    - pyzmq 25.1.2 py38hdecc13b_0
    - setuptools 69.1.1 pyhd8ed1ab_0
    - six 1.16.0 pyh6c4a22f_0
    - stack_data 0.6.2 pyhd8ed1ab_0
    - tk 8.6.13 h5226925_1
    - tomli 2.0.1 pyhd8ed1ab_0
    - tornado 6.4 py38h91455d4_0
    - traitlets 5.14.1 pyhd8ed1ab_0
    - trove-classifiers 2024.2.23 pyhd8ed1ab_0
    - typing_extensions 4.10.0 pyha770c72_0
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 hcf57466_18
    - vc14_runtime 14.38.33130 h82b7239_18
    - vs2015_runtime 14.38.33130 hcb4865c_18
    - wcwidth 0.2.13 pyhd8ed1ab_0
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
    - zeromq 4.3.5 h63175ca_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - __win
    - comm >=0.1.1
    - debugpy >=1.6.5
    - ipython >=7.23.1
    - jupyter_client >=6.1.12
    - jupyter_core >=4.12,!=5.0.*
    - matplotlib-inline >=0.1
    - nest-asyncio
    - packaging
    - psutil
    - python >=3.8
    - pyzmq >=24
    - tornado >=6.1
    - traitlets >=5.4.0
test:
  commands:
    - pip check
    - jupyter kernelspec list
  imports:
    - ipykernel
  requires:
    - flaky
    - ipyparallel
    - matplotlib-base
    - numpy
    - pip
    - pytest >=7.0
    - pytest-asyncio >=0.23.5
    - pytest-cov
    - pytest-timeout
    - python !=3.8
  source_files:
    - tests
about:
  description: 'A powerful interactive Python shell and a Jupyter kernel to work with

    Python code in Jupyter notebooks and other interactive frontends.

    '
  dev_url: https://github.com/ipython/ipykernel
  doc_source_url: https://github.com/ipython/ipykernel/blob/master/docs/index.rst
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: IPython Kernel for Jupyter
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240226.8.1
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - davidbrochart
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/ipykernel-feedstock
  sha: 40cb9443c57513547238c72bdf8f9422b9b2b6f9
