# This file created by conda-build 3.23.1
# meta.yaml template originally from:
# C:\Users\builder\stiwari\aggregate\tensorflow_recipes\tensorboard, last modified Tue Nov 29 16:22:27 2022
# ------------------------------------------------

package:
  name: tensorboard
  version: 2.10.0
source:
  sha256: 76c91a5e8959cd2208cc32cb17a0cb002badabb66a06ac2af02a7810f49a59e3
  url: https://pypi.io/packages/py3/t/tensorboard/tensorboard-2.10.0-py3-none-any.whl
build:
  entry_points:
    - tensorboard = tensorboard.main:run_main
  number: '0'
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard-2.10.0-py3-none-any.whl
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.2.2 py38haa95532_0
    - python 3.8.15 h6244533_2
    - setuptools 65.5.0 py38haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - absl-py >=0.4
    - google-auth-oauthlib >=0.4.1,<0.5
    - grpcio >=1.24.3
    - markdown >=2.6.8
    - numpy >=1.12.0
    - protobuf >=3.6.0
    - python >=3.8,<3.9.0a0
    - requests >=2.21.0,<3
    - setuptools >=41.0.0
    - tensorboard-data-server >=0.6.0,<0.7.0
    - tensorboard-plugin-wit >=1.6.0
    - werkzeug >=1.0.1
    - wheel >=0.26
test:
  commands:
    - tensorboard -h
  imports:
    - tensorboard
about:
  dev_url: https://github.com/tensorflow/tensorboard
  doc_url: https://www.tensorflow.org/tensorboard/get_started
  home: https://www.tensorflow.org/tensorboard
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: TensorFlow's Visualization Toolkit
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - farhantejani
    - gilbertfrancois
    - jschueller
    - mdraw
    - sdvillal
