# This file created by conda-build 3.21.8
# meta.yaml template originally from:
# C:\ci\containers\0000283lsgd\tmp\build\80754af9\rsync-recipes\re2-2022.04.01-on-winbuilder, last modified Fri May 13 03:51:09 2022
# ------------------------------------------------

package:
  name: re2
  version: 2022.04.01
source:
  fn: re2-2022-04-01.tar.gz
  sha256: 1ae8ccfdb1066a731bba6ee0881baad5efd2cd661acd9569b689f2586e1a50e9
  url: http://github.com/google/re2/archive/2022-04-01.tar.gz
build:
  detect_binary_files_with_prefix: true
  missing_dso_whitelist:
    - $RPATH/ld64.so.1
  number: '0'
  run_exports:
    - re2 >=2022.4.1,<2022.4.2.0a0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h8cc25b3_1
    - zlib 1.2.12 h8cc25b3_2
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - if not exist %PREFIX%\\Library\\include\\re2\\re2.h exit 1
    - if not exist %PREFIX%\\Library\\lib\\re2.lib exit 1
    - if exist %PREFIX%\\Library\\lib\\re2_static.lib exit 1
    - if not exist %PREFIX%\\Library\\bin\\re2.dll exit 1
about:
  dev_url: https://github.com/google/re2/
  doc_url: https://github.com/google/re2/wiki
  home: https://github.com/google/re2/
  license: BSD-3-Clause
  license_file: LICENSE
  summary: 'RE2 is a fast, safe, thread-friendly alternative to backtracking regular
    expression

    engines like those used in PCRE, Perl, and Python. It is a C++ library.

    '
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - kszucs
    - pitrou
    - scopatz
    - wesm
    - xhochy
