# This file created by conda-build 3.25.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri Sep 29 07:45:33 2023
# ------------------------------------------------

package:
  name: pywin32
  version: '306'
source:
  patches:
    - 0003-remove-PATH-pth-hack.patch
    - do-not-build-scintilla.patch
  sha256: 16e5ad3efbbf997080f67c3010bd4eb0067d499bbade9be1b240b7e85325c167
  url: https://github.com/mhammond/pywin32/archive/b306.tar.gz
build:
  number: '2'
  string: py38hd3f51b4_2
requirements:
  build:
    - vs2019_win-64 19.29.30139 he1865b1_17
    - vswhere 3.1.4 h57928b3_0
  host:
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2023.7.22 h56e8100_0
    - libffi 3.4.2 h8ffe710_5
    - libsqlite 3.43.0 hcfcfb64_0
    - libzlib 1.2.13 hcfcfb64_5
    - openssl 3.1.3 hcfcfb64_0
    - pip 23.2.1 pyhd8ed1ab_0
    - python 3.8.17 h4de0772_0_cpython
    - setuptools 68.2.2 pyhd8ed1ab_0
    - tk 8.6.13 hcfcfb64_0
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 h64f974e_17
    - vc14_runtime 14.36.32532 hdcecf7f_17
    - vs2015_runtime 14.36.32532 h05e6639_17
    - wheel 0.41.2 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
  run:
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - ucrt >=10.0.20348.0
    - vc >=14.2,<15
    - vc14_runtime >=14.29.30139
test:
  requires:
    - python >=3.8,<3.9.0a0
about:
  description: 'A set of extension modules that provides access to many of the Windows
    API functions.

    '
  dev_url: https://github.com/mhammond/pywin32
  home: https://github.com/mhammond/pywin32
  license: PSF-2.0
  license_file: Pythonwin/License.txt
  summary: Python extensions for Windows
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - carlodri
    - mingwandroid
    - nicoddemus
    - xhochy
