# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_8d5_fdq9d2\clone\recipe, last modified Fri Mar  3 11:07:49 2023
# ------------------------------------------------

package:
  name: libpng
  version: 1.6.39
source:
  patches:
    - 0001-Include-pkg-config-files-in-the-Windows-packages-too.patch
    - 0002-Ensure-that-lm-is-not-included-in-Windows-pkg-config.patch
  sha256: af4fb7f260f839919e5958e5ab01a275d4fe436d45442a36ee62f73e5beb75ba
  url: https://download.sourceforge.net/libpng/libpng-1.6.39.tar.gz
build:
  number: '0'
  run_exports:
    - libpng >=1.6.39,<1.7.0a0
  string: h8cc25b3_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_6
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1t h2bbff1b_0
    - python 3.11.0 h966fe2a_3
    - sqlite 3.40.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022g h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_0
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - echo "tests done during build ..."
about:
  description: 'libpng is the official PNG reference library. It supports almost all
    PNG

    features, is extensible, and has been extensively tested for over 20 years.

    '
  dev_url: https://sourceforge.net/p/libpng/code/ci/libpng16/tree/
  doc_url: http://www.libpng.org/pub/png/libpng.html
  home: http://www.libpng.org/pub/png/libpng.html
  license: Zlib
  license_family: Other
  license_file: LICENSE
  summary: PNG reference library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8da214e1-1b94-435e-85cb-41cb78fbfb7b
  recipe-maintainers:
    - msarahan
    - ocefpaf
    - pkgw
  remote_url: git@github.com:AnacondaRecipes/libpng-feedstock.git
  sha: cb4734baa7676085ec79b6d3a95cba5460ef27a7
