# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/pyasn1-feedstock/recipe, last modified Sat Aug  7 09:29:54 2021
# ------------------------------------------------

package:
  name: pyasn1
  version: 0.4.8
source:
  sha256: aef77c9fb94a3ac588e87841208bdec464471d9871bd5050a287cc9a475cd0ba
  url: https://pypi.org/packages/source/p/pyasn1/pyasn1-0.4.8.tar.gz
build:
  noarch: python
  number: '0'
  script: /Users/ktietz/demo/mc3/conda-bld/pyasn1_1629708007385/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/bin/python
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: pyhd3eb1b0_0
requirements:
  host:
    - ca-certificates 2021.7.5 hca03da5_1
    - certifi 2021.5.30 py39hca03da5_0
    - expat 2.4.1 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.3 hc377ac9_2
    - libiconv 1.16 h1230e6a_0
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.3 py39hca03da5_0
    - python 3.9.6 hc70090a_5
    - readline 8.1 h1a28f6b_0
    - setuptools 52.0.0 py39hca03da5_0
    - sqlite 3.36.0 h1058600_0
    - tk 8.6.10 hb8d0fd4_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.37.0 pyhd3eb1b0_1
    - xz 5.2.5 h1a28f6b_0
    - zlib 1.2.11 hca03da5_3
  run:
    - python
test:
  imports:
    - pyasn1
    - pyasn1.codec
    - pyasn1.codec.ber
    - pyasn1.codec.cer
    - pyasn1.codec.der
    - pyasn1.compat
    - pyasn1.type
about:
  description: 'Pure-Python implementation of ASN.1 types and DER/BER/CER codecs (X.208)

    '
  dev_url: https://github.com/etingof/pyasn1
  doc_source_url: https://github.com/etingof/pyasn1/blob/master/doc/source/contents.rst
  doc_url: http://pyasn1.sourceforge.net/
  home: https://github.com/etingof/pyasn1
  license: BSD 2-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: ASN.1 types and codecs
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - pmlandwehr
