# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\Users\dev-admin\aggregate\mkl-service-feedstock\recipe, last modified Mon May  1 20:49:26 2023
# ------------------------------------------------

package:
  name: mkl-service
  version: 2.4.0
source:
  patches:
    - patches/0001-Conditional-mpich2.patch
  sha256: 7c515b7a1442c58b81c027fd13d188b28283df7c4d7df615e0c2f7618eb4a69c
  url: https://github.com/IntelPython/mkl-service/archive/v2.4.0.post0.tar.gz
build:
  ignore_run_exports:
    - blas
    - mkl-service
  number: '1'
  string: py38h2bbff1b_1
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - blas 1.0 mkl
    - ca-certificates 2023.01.10 haa95532_0
    - cython 0.29.33 py38hd77b12b_0
    - intel-openmp 2023.1.0 h59b6b97_46319
    - libffi 3.4.2 hd77b12b_6
    - mkl 2023.1.0 h8bd8f75_46356
    - mkl-devel 2023.1.0 h74d85ca_46356
    - mkl-include 2023.1.0 haa95532_46356
    - openssl 1.1.1t h2bbff1b_0
    - python 3.8.16 h6244533_3
    - setuptools 66.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tbb 2021.8.0 h59b6b97_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - mkl >=2023.1.0,<2024.0a0
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - nosetests -v tests
  imports:
    - mkl
  requires:
    - nose
    - six
  source_files:
    - tests
about:
  description: Intel(R) Math Kernel Library (Intel(R) MKL) support functions are subdivided
    into the following groups according to their purpose, such as Version Information
    Threading Control Timing Memory Management Conditional Numerical Reproducibility
    Control Miscellaneous
  dev_url: https://github.com/IntelPython/mkl-service
  doc_url: https://github.com/IntelPython/mkl-service
  home: https://github.com/IntelPython/mkl-service
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: Python hooks for Intel(R) Math Kernel Library runtime control settings.
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - oleksandr-pavlyk
