c_compiler:
  - clang_bootstrap  # [osx]
  - gcc              # [linux]
  - vs2019           # [win]
cxx_compiler:
  - clang_bootstrap  # [osx]
  - gxx              # [linux]
  - vs2019           # [win]

# Starting from LLVM 14, the ABI of libclang doesn't necessarily
# match the major version anymore - cf. #170 and
# https://github.com/llvm/llvm-project/issues/54004
libclang_soversion:
  - 13

variant:
  - default
  # - hcc   # [linux]
