# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_88mdhvtahm\clone\recipe, last modified Fri Dec 30 08:11:43 2022
# ------------------------------------------------

package:
  name: kiwisolver
  version: 1.4.4
source:
  sha256: d41997519fcba4a1e46eb4a2fe31bc12f0ff957b2b81bac28db24744f333e955
  url: https://pypi.io/packages/source/k/kiwisolver/kiwisolver-1.4.4.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_88mdhvtahm\\croot\\kiwisolver_1672387921783\\_h_env\\python.exe
    -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  string: py38hd77b12b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.12.7 py38haa95532_0
    - cppy 1.2.1 py38haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - packaging 22.0 py38haa95532_0
    - pip 22.3.1 py38haa95532_0
    - python 3.8.15 h6244533_2
    - setuptools 65.5.0 py38haa95532_0
    - setuptools-scm 7.0.4 py38haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - toml 0.10.2 pyhd3eb1b0_0
    - tomli 2.0.1 py38haa95532_0
    - typing-extensions 4.4.0 py38haa95532_0
    - typing_extensions 4.4.0 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check || 1
  imports:
    - kiwisolver
  requires:
    - pip
about:
  description: 'Kiwi is an implementation of the algorithm based on the seminal

    Cassowary paper.It is not a refactoring of the original C++ solver.

    Kiwi has been designed from the ground up to be lightweight and fast.

    '
  dev_url: https://github.com/nucleic/kiwi
  doc_url: https://kiwisolver.readthedocs.io/
  home: https://github.com/nucleic/kiwi
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: An efficient C++ implementation of the Cassowary constraint solver
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 882c4d93-15bb-430a-8cf5-475198821f42
  recipe-maintainers:
    - MatthieuDartiailh
    - blink1073
    - ericdill
    - licode
    - ocefpaf
    - sccolbert
    - tacaswell
  remote_url: git@github.com:AnacondaRecipes/kiwisolver-feedstock.git
  sha: 3865c39ac47fe7536c61298736cc24d6ae40105a
