# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_f4do8t8jfs\clone\recipe, last modified Mon Sep 11 15:59:58 2023
# ------------------------------------------------

package:
  name: cryptography
  version: 41.0.3
source:
  sha256: 6d192741113ef5e30d89dcb5b956ef4e1578f304708701b8b73d38e3e1461f34
  url: https://pypi.io/packages/source/c/cryptography/cryptography-41.0.3.tar.gz
build:
  number: '0'
  script:
    - set OPENSSL_DIR=%LIBRARY_PREFIX%
    - C:\\b\\abs_f4do8t8jfs\\croot\\cryptography_1694444424531\\_h_env\\python.exe
      -m pip install . -vv --no-deps --no-build-isolation
  string: py38h3438e0d_0
requirements:
  build:
    - rust 1.71.1 haa95532_0
    - rust_win-64 1.71.1 hd77b12b_0
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - cffi 1.15.1 py38h2bbff1b_3
    - libffi 3.4.4 hd77b12b_0
    - openssl 1.1.1v h2bbff1b_0
    - pip 23.2.1 py38haa95532_0
    - pycparser 2.21 pyhd3eb1b0_0
    - python 3.8.17 h6244533_0
    - semantic_version 2.8.5 pyhd3eb1b0_0
    - setuptools 68.0.0 py38haa95532_0
    - setuptools-rust 1.5.2 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - typing_extensions 4.7.1 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - cffi >=1.12
    - openssl >=1.1.1v,<1.1.2a
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - pytest -n auto
  requires:
    - cryptography-vectors 41.0.3.*
    - pip
    - pretend
    - pytest >=6.2.0
    - pytest-benchmark
    - pytest-cov
    - pytest-xdist
  source_files:
    - pyproject.toml
    - tests
about:
  description: 'Cryptography is a package which provides cryptographic recipes and

    primitives to Python developers. Our goal is for it to be your

    "cryptographic standard library". It supports Python 3.6+ and PyPy3 7.2+.

    cryptography includes both high level recipes and low level interfaces to

    common cryptographic algorithms such as symmetric ciphers, message digests,

    and key derivation functions.

    '
  dev_url: https://github.com/pyca/cryptography
  doc_url: https://cryptography.io/en/41.0.3/
  home: https://github.com/pyca/cryptography
  license: (BSD-3-Clause OR Apache-2.0) AND PSF-2.0 AND MIT
  license_family: BSD
  license_url: https://github.com/pyca/cryptography/blob/41.0.3/vectors/LICENSE
  summary: Provides cryptographic recipes and primitives to Python developers
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f49e27ad-5451-4605-ae25-bb8a6901e43b
  recipe-maintainers:
    - chenghlee
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/cryptography-feedstock.git
  sha: 9a5d0096892ec8c0a990026fef0b641160dcfaa1
