# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_19i1y8ykas\clone\recipe, last modified Mon Sep 18 18:30:03 2023
# ------------------------------------------------

package:
  name: mkl_fft
  version: 1.3.8
source:
  patches:
    - 0001-install_requires-mkl-service.patch
  sha256: 5d0976eb4bc174dd3338b634bfc957e33868c9dc439a63dc25e1e6f6ab159662
  url: https://github.com/IntelPython/mkl_fft/archive/v1.3.8.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_19i1y8ykas\\croot\\mkl_fft_1695058226480\\_h_env\\python.exe
    -m pip install --no-build-isolation --no-deps .
  script_env:
    - MKLROOT=C:\b\abs_19i1y8ykas\croot\mkl_fft_1695058226480\_h_env
  string: py38h2bbff1b_0
requirements:
  build:
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - blas 1.0 mkl
    - ca-certificates 2023.08.22 haa95532_0
    - cython 3.0.0 py38h2bbff1b_0
    - intel-openmp 2023.1.0 h59b6b97_46319
    - libffi 3.4.4 hd77b12b_0
    - mkl 2023.1.0 h6b88ed4_46357
    - mkl-devel 2023.1.0 h670ff1c_46357
    - mkl-include 2023.1.0 haa95532_46357
    - mkl-service 2.4.0 py38h2bbff1b_1
    - numpy-base 1.21.5 py38h46c4fa8_4
    - openssl 3.0.10 h2bbff1b_2
    - pip 23.2.1 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tbb 2021.8.0 h59b6b97_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - blas 1.0 mkl
    - mkl >=2023.1.0,<2024.0a0
    - mkl-service >=2.3.0,<3.0a0
    - numpy
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pytest -v --pyargs mkl_fft
    - pip check
  imports:
    - mkl_fft
    - mkl_fft._numpy_fft
    - mkl_fft._scipy_fft
    - mkl_fft.interfaces
    - mkl_fft.interfaces.numpy_fft
    - mkl_fft.interfaces.scipy_fft
  requires:
    - pip
    - pytest
about:
  description: NumPy-based implementation of Fast Fourier Transform using Intel (R)
    Math Kernel Library. Supports in-place and out-of-place, 1D and ND complex FFT
    on arrays of single and double precision with arbitrary memory layout, so long
    as array strides are multiples of its itemsize.
  dev_url: https://github.com/IntelPython/mkl_fft
  doc_url: https://github.com/IntelPython/mkl_fft
  home: https://github.com/IntelPython/mkl_fft
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: NumPy-based implementation of Fast Fourier Transform using Intel (R) Math
    Kernel Library.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 190db563-3e3d-4c01-ab94-259da1ea298f
  recipe-maintainers:
    - oleksandr-pavlyk
  remote_url: git@github.com:AnacondaRecipes/mkl_fft-feedstock.git
  sha: c70fbdab94fff01b8d9334ef0701c6f911e9dea5
