# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_16qe7jhw7n\clone\recipe, last modified Thu Nov 10 12:50:35 2022
# ------------------------------------------------

package:
  name: termcolor
  version: 2.1.0
source:
  sha256: b80df54667ce4f48c03fe35df194f052dc27a541ebbf2544e4d6b47b5d6949c4
  url: https://pypi.io/packages/source/t/termcolor/termcolor-2.1.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_16qe7jhw7n\\croot\\termcolor_1668084642458\\_h_env\\python.exe
    -m pip install . -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - editables 0.3 py38haa95532_0
    - hatch-vcs 0.2.0 py38haa95532_0
    - hatchling 1.8.0 py38haa95532_0
    - openssl 1.1.1s h2bbff1b_0
    - packaging 21.3 pyhd3eb1b0_0
    - pathspec 0.9.0 py38haa95532_0
    - pip 22.2.2 py38haa95532_0
    - pluggy 1.0.0 py38haa95532_1
    - pyparsing 3.0.9 py38haa95532_0
    - python 3.8.13 h6244533_1
    - setuptools 65.5.0 py38haa95532_0
    - setuptools-scm 7.0.4 py38haa95532_0
    - sqlite 3.39.3 h2bbff1b_0
    - tomli 2.0.1 py38haa95532_0
    - typing-extensions 4.3.0 py38haa95532_0
    - typing_extensions 4.3.0 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  imports:
    - termcolor
  requires:
    - pip
about:
  description: 'ANSI color formatting for output in terminal.

    '
  dev_url: https://github.com/termcolor/termcolor
  doc_url: https://github.com/termcolor/termcolor/blob/main/README.md
  home: https://github.com/termcolor/termcolor
  license: MIT
  license_family: MIT
  license_file: COPYING.txt
  summary: ANSII Color formatting for output in terminal.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 169b6e8f-e327-4297-ba16-7741f04d6c0b
  recipe-maintainers:
    - jakirkham
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/termcolor-feedstock.git
  sha: 268bf997e3df51436726877dfe24ae8d6be7fd09
