# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# C:\b\abs_54ewdv1o4x\clone\recipe, last modified Thu Aug 17 18:39:12 2023
# ------------------------------------------------

package:
  name: icu
  version: '73.1'
source:
  - patches:
      - icu-22356.patch
      - icu-config.patch
      - icu4c-4_9_1-mingw-w64-mkdir-compatibility.patch
    sha256: a457431de164b4aa7eca00ed134d00dfbf88a77c6986a10ae7774fc076bb8c45
    url: https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-src.tgz
  - folder: source/data
    sha256: 07d7557efb30fc2e9b74652f1525603b3209a4539d2d345d704e3df3bf9b957e
    url: https://github.com/unicode-org/icu/releases/download/release-73-1/icu4c-73_1-data.zip
build:
  number: '0'
  run_exports:
    - icu >=73.1,<74.0a0
  string: h6c2663c_0
requirements:
  build:
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - m2-base 1.0.0 3
    - m2-bash 4.3.042 5
    - m2-bash-completion 2.3 2
    - m2-catgets 1.1 3
    - m2-coreutils 8.25 102
    - m2-dash 0.5.8 2
    - m2-diffutils 3.3 4
    - m2-file 5.25 2
    - m2-filesystem 2016.04 4
    - m2-findutils 4.6.0 2
    - m2-gawk 4.1.3 2
    - m2-gcc-libs 5.3.0 4
    - m2-gettext 0.19.7 4
    - m2-gmp 6.1.0 3
    - m2-grep 2.22 4
    - m2-gzip 1.7 2
    - m2-inetutils 1.9.2 2
    - m2-info 6.0 2
    - m2-less 481 2
    - m2-libasprintf 0.19.7 4
    - m2-libbz2 1.0.6 3
    - m2-libcatgets 1.1 3
    - m2-libcrypt 1.3 2
    - m2-libgettextpo 0.19.7 4
    - m2-libiconv 1.14 3
    - m2-libintl 0.19.7 4
    - m2-liblzma 5.2.2 2
    - m2-libpcre 8.38 2
    - m2-libreadline 6.3.008 8
    - m2-libutil-linux 2.26.2 2
    - m2-libxml2 2.9.2 3
    - m2-make 4.1 5
    - m2-mintty 1!2.2.3 2
    - m2-mpfr 3.1.4 2
    - m2-msys2-launcher-git 0.3.28.860c495 2
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-ncurses 6.0.20160220 2
    - m2-patch 2.7.5 2
    - m2-sed 4.2.2 3
    - m2-tar 1.28 4
    - m2-tftp-hpa 5.2 2
    - m2-time 1.7 2
    - m2-ttyrec 1.0.8 2
    - m2-tzcode 2015.e 2
    - m2-unzip 6.0 3
    - m2-util-linux 2.26.2 2
    - m2-which 2.21 3
    - m2-zip 3.0 2
    - m2-zlib 1.2.8 4
    - msys2-conda-epoch 20160418 1
    - openssl 3.0.10 h2bbff1b_0
    - posix 1.0.0 2
    - python 3.8.17 h1aa4202_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
  run:
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - genbrk --help
    - gencfu --help
    - gencnval --help
    - gendict --help
    - icuinfo --help
    - makeconv gb-18030-2000.ucm
  files:
    - de.txt
    - gb-18030-2000.ucm
about:
  description: 'ICU is a mature, widely used set of C/C++ and Java libraries providing

    Unicode and Globalization support for software applications. ICU is

    widely portable and gives applications the same results on all platforms

    and between C/C++ and Java software.

    '
  dev_url: https://github.com/unicode-org/icu
  doc_url: https://unicode-org.github.io/icu/
  home: https://icu.unicode.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: International Components for Unicode.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 54d48c4c-7cfa-410a-9d34-c8e019d751c2
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - msarahan
    - ocefpaf
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/icu-feedstock.git
  sha: be820b07c5e0bff9e01e173920897db1b55e815a
