# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Fri May  5 12:16:10 2023
# ------------------------------------------------

package:
  name: ipython
  version: 8.12.2
source:
  sha256: c7b80eb7f5a855a88efc971fda506ff7a91c280b42cdae26643e0f601ea281ea
  url: https://pypi.io/packages/source/i/ipython/ipython-8.12.2.tar.gz
build:
  entry_points:
    - ipython = IPython:start_ipython
    - ipython3 = IPython:start_ipython
  noarch: python
  number: '0'
  script: D:\\bld\\ipython_1683289169355\\_h_env\\python.exe -m pip install . -vv
    --no-deps
  script_env:
    - COV_THRESHOLD=70
    - IPYTHON_TESTING_TIMEOUT_SCALE=10
    - MIGRATING=False
  string: pyh08f2357_0
requirements:
  host:
    - bzip2 1.0.8 h8ffe710_4
    - ca-certificates 2022.12.7 h5b45459_0
    - libexpat 2.5.0 h63175ca_1
    - libffi 3.4.2 h8ffe710_5
    - libsqlite 3.40.0 hcfcfb64_1
    - libzlib 1.2.13 hcfcfb64_4
    - openssl 3.1.0 hcfcfb64_3
    - pip 23.1.2 pyhd8ed1ab_0
    - python 3.11.3 h2628c8c_0_cpython
    - setuptools 67.7.2 pyhd8ed1ab_0
    - tk 8.6.12 h8ffe710_0
    - tzdata 2023c h71feb2d_0
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 hb25d44b_16
    - vc14_runtime 14.34.31931 h5081d32_16
    - vs2015_runtime 14.34.31931 hed1258a_16
    - wheel 0.40.0 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
  run:
    - __win
    - backcall
    - colorama
    - decorator
    - jedi >=0.16
    - matplotlib-inline
    - pickleshare
    - prompt_toolkit >=3.0.30,<3.1.0,!=3.0.37
    - pygments >=2.4.0
    - python >=3.8
    - stack_data
    - traitlets >=5
    - typing_extensions
test:
  commands:
    - pip check
    - pygmentize -L | grep ipython
    - ipython -h
    - ipython3 -h
    - mypy -p IPython
  imports:
    - IPython
    - IPython.core
    - IPython.core.magics
    - IPython.core.tests
    - IPython.extensions
    - IPython.extensions.tests
    - IPython.external
    - IPython.lib
    - IPython.lib.tests
    - IPython.sphinxext
    - IPython.terminal
    - IPython.terminal.pt_inputhooks
    - IPython.terminal.tests
    - IPython.testing
    - IPython.testing.plugin
    - IPython.testing.tests
    - IPython.utils
    - IPython.utils.tests
  requires:
    - black
    - curio
    - m2-grep
    - matplotlib-base !=3.2.0
    - mypy
    - nbformat
    - numpy >=1.21
    - pandas
    - pip
    - pygments
    - pytest <7.1
    - pytest-asyncio
    - pytest-cov
    - testpath
    - trio
    - types-decorator
  source_files:
    - pyproject.toml
about:
  description: 'IPython provides a rich architecture for interactive computing with

    a powerful interactive shell, a kernel for Jupyter, high performance

    tools for parallel computing, and more.

    '
  dev_url: https://github.com/ipython/ipython
  doc_url: https://ipython.readthedocs.io
  home: https://ipython.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: 'IPython: Productive Interactive Computing'
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - Carreau
    - blink1073
    - bollwyvl
    - ellisonbg
    - fperez
    - jakirkham
    - minrk
    - ocefpaf
    - pelson
    - takluyver
