# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: grpc-cpp
  version: 1.48.2
source:
  patches:
    - patches/0001-Monkey-patch-distutils.ccompiler.spawn-to-elide-std-.patch
    - patches/0001-fix-win-commands.patch
    - patches/0002-windows-ssl-lib-names.patch
    - patches/0003-Link-against-grpc.patch
    - patches/force-protoc-executable.patch
  sha256: bdb8e98145469d58c69ab9f2c9e0bd838c2836a99b5760bc0ebf658623768f52
  url: https://github.com/grpc/grpc/archive/v1.48.2.tar.gz
build:
  ignore_run_exports:
    - abseil-cpp
    - c-ares
    - libprotobuf
    - openssl
    - re2
    - zlib
  missing_dso_whitelist: null
  number: 0
  run_exports:
    - grpc-cpp >=1.48.2,<1.49.0a0
  script_env:
    - LIB_EXT=.lib
    - STATIC_BUILD=yes
  string: hf108199_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_6
    - libprotobuf 3.20.3 h23ce68f_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - m2-msys2-runtime 2.5.0.17080.65c939c 3
    - m2-patch 2.7.5 2
    - msys2-conda-epoch 20160418 1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1t h2bbff1b_0
    - python 3.11.2 h966fe2a_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - abseil-cpp 20211102.0 hd77b12b_0
    - c-ares 1.19.0 h2bbff1b_0
    - ca-certificates 2023.01.10 haa95532_0
    - libprotobuf 3.20.3 h23ce68f_0
    - openssl 1.1.1t h2bbff1b_0
    - re2 2022.04.01 hd77b12b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_0
  run:
    - libprotobuf >=3.20.3,<3.20.4.0a0
    - re2
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  files:
    - tests/include/*
  requires:
    - cmake
    - ninja
    - pkg-config
    - vs2017_win-64
  script: run_test_cpp.bat
about:
  description: 'gRPC is a modern, open source, high-performance remote procedure call

    (RPC) framework that can run anywhere. gRPC enables client and server

    applications to communicate transparently, and simplifies the building

    of connected systems.


    This package contains the gRPC C++ libraries and header files, as well

    as the code generation plugins.

    '
  dev_url: https://github.com/grpc/grpc
  doc_url: https://grpc.io/docs/
  home: https://grpc.io/
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE
  summary: gRPC - A high-performance, open-source universal RPC framework
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: cc800219-7cd0-4f6d-9250-9c011873302c
  recipe-maintainers:
    - mingwandroid
    - pitrou
    - wesm
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/grpc-cpp-feedstock.git
  sha: 8a0c86d8191910d174fa7b84ca2e123c6387e30f
