# This file created by conda-build 24.1.1
# meta.yaml template originally from:
# C:\b\abs_4etpfrkumr\clone\recipe, last modified Mon Feb 12 20:43:11 2024
# ------------------------------------------------

package:
  name: urllib3
  version: 2.1.0
source:
  sha256: df7aa8afb0148fa78488e7899b2c59b5f4ffcfa82e6c54ccb9dd37c1d7b52d54
  url: https://pypi.io/packages/source/u/urllib3/urllib3-2.1.0.tar.gz
build:
  number: '1'
  script: C:\\b\\abs_4etpfrkumr\\croot\\urllib3_1707770616184\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py38haa95532_1
requirements:
  host:
    - ca-certificates 2023.12.12 haa95532_0
    - editables 0.3 py38haa95532_0
    - hatchling 1.18.0 py38haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.13 h2bbff1b_0
    - packaging 23.1 py38haa95532_0
    - pathspec 0.10.3 py38haa95532_0
    - pip 23.3.1 py38haa95532_0
    - pluggy 1.0.0 py38haa95532_1
    - python 3.8.18 h1aa4202_0
    - setuptools 68.2.2 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tomli 2.0.1 py38haa95532_0
    - trove-classifiers 2023.10.18 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py38haa95532_0
  run:
    - brotli-python >=1.0.9
    - pysocks >=1.5.6,<2.0,!=1.5.7
    - python >=3.8,<3.9.0a0
  run_constrained:
    - requests >=2.26.0
    - selenium >=4.4.3
    - zstandard >=0.18.0
test:
  commands:
    - pip check
  imports:
    - urllib3
    - urllib3.contrib
    - urllib3.util
  requires:
    - pip
about:
  description: 'urllib3 is a powerful, sanity-friendly HTTP client for Python. Much
    of the

    Python ecosystem already uses urllib3. urllib3 brings many critical features

    that are missing from the Python standard libraries, such as thread safety,

    connection pooling, client side ssl/tls verification, support for gzip and

    deflate encodings, HTTP and SOCKS proxy support, helpers for retrying requests

    and dealing with HTTP redirects.

    '
  dev_url: https://github.com/urllib3/urllib3
  doc_url: https://urllib3.readthedocs.io/
  home: https://urllib3.readthedocs.io/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: HTTP library with thread-safe connection pooling, file post, and more.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 4e6badab-551a-467e-9b49-3ce39602225f
  recipe-maintainers:
    - ocefpaf
    - pmlandwehr
    - sethmlarson
    - sigmavirus24
  remote_url: git@github.com:AnacondaRecipes/urllib3-feedstock.git
  sha: 31e394c340638a01d7a085d5520deb2275b8bd20
