# This file created by conda-build 3.28.1
# ------------------------------------------------

package:
  name: vs2015_runtime
  version: 14.38.33130
source:
  - sha256: 4dfe83c91124cd542f4222fe2c396cabeac617bb6f59bdcbdf89fd6f0df0a32f
    url: https://download.visualstudio.microsoft.com/download/pr/a061be25-c14a-489a-8c7c-bb72adfb3cab/4DFE83C91124CD542F4222FE2C396CABEAC617BB6F59BDCBDF89FD6F0DF0A32F/vc_redist.x64.exe
build:
  number: 18
  string: hcb4865c_18
requirements:
  build: []
  run:
    - vc14_runtime >=14.38.33130
about:
  home: https://github.com/conda-forge/vc-feedstock
  license: BSD-3-Clause
  license_family: BSD
  summary: A backwards compatible meta-package. See vc14_runtime for the new package.
extra:
  copy_test_source_files: true
  feedstock-name: vc
  final: true
  flow_run_id: azure_20231213.1.1
  recipe-maintainers:
    - 183amir
    - isuruf
    - jakirkham
    - msarahan
    - patricksnape
    - pelson
  remote_url: https://github.com/conda-forge/vc-feedstock
  sha: 8725d3429b35eb8b12897a015925ef4d2a135edc
