# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_e4nt8ttmb0\clone\recipe, last modified Wed Jun  7 19:52:17 2023
# ------------------------------------------------

package:
  name: hdf5
  version: 1.12.1
source:
  patches: null
  sha256: 79c66ff67e666665369396e9c90b32e238e501f345afd2234186bfb8331081ca
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.12/hdf5-1.12.1/src/hdf5-1.12.1.tar.gz
build:
  ignore_run_exports: null
  number: '3'
  run_exports:
    - hdf5 >=1.12.1,<1.12.2.0a0
  string: h51c971a_3
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.22.1 h9ad04ae_0
    - intel-fortran_win-64 2022.1.0 h950cae3_2
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - icc_rt 2022.1.0 h6049295_2
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_0
  run:
    - icc_rt >=2022.1.0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - where gif2h5
    - where h52gif
    - where h5copy
    - where h5debug
    - where h5diff
    - where h5dump
    - where h5import
    - where h5jam
    - where h5ls
    - where h5mkgrp
    - where h5repack
    - where h5repart
    - where h5stat
    - where h5unjam
    - if not exist %PREFIX%\\Library\\lib\\hdf5.lib exit 1
    - if not exist %PREFIX%\\Library\\bin\\hdf5.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\hdf5_cpp.lib exit 1
    - if not exist %PREFIX%\\Library\\bin\\hdf5_cpp.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\hdf5_hl.lib exit 1
    - if not exist %PREFIX%\\Library\\bin\\hdf5_hl.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\hdf5_hl_cpp.lib exit 1
    - if not exist %PREFIX%\\Library\\bin\\hdf5_hl_cpp.dll exit 1
  files:
    - compound_fortran2003.f90
    - h5_cmprss.c
    - h5_cmprss.f90
    - h5tutr_cmprss.cpp
  requires:
    - intel-fortran_win-64 2022.1.0.*
    - vs2017_win-64
about:
  description: 'HDF5 supports an unlimited variety of datatypes, and is designed for

    flexible and efficient I/O and for high volume and complex data.

    '
  dev_url: https://docs.hdfgroup.org/hdf5/develop/
  doc_url: https://docs.hdfgroup.org/hdf5/develop/
  home: https://www.hdfgroup.org/solutions/hdf5/
  license: OTHER
  license_family: BSD
  license_file:
    - COPYING
    - COPYING_LBNL_HDF5
  summary: HDF5 is a data model, library, and file format for storing and managing
    data
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: e496e38e-c8f4-4086-b71d-c49a7a306384
  recipe-maintainers:
    - astrofrog
    - gillins
    - groutr
    - jakirkham
    - marqh
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/hdf5-feedstock.git
  sha: c9bf72758146db8f7085428c1344a28f520ea211
