# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_aarblxbilo\clone\recipe, last modified Thu Oct 20 21:44:20 2022
# ------------------------------------------------

package:
  name: ruamel.yaml.clib
  version: 0.2.6
source:
  sha256: 4ff604ce439abb20794f05613c374759ce10e3595d1867764dd1ae675b85acbd
  url: https://pypi.io/packages/source/r/ruamel.yaml.clib/ruamel.yaml.clib-0.2.6.tar.gz
build:
  ignore_run_exports:
    - python
  number: '1'
  script: C:\\b\\abs_aarblxbilo\\croot\\ruamel.yaml.clib_1666302270884\\_h_env\\python.exe
    -m pip install . -vv
  string: py38h2bbff1b_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.2.2 py38haa95532_0
    - python 3.8.13 h6244533_0
    - setuptools 63.4.1 py38haa95532_0
    - sqlite 3.39.3 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - _ruamel_yaml
  requires:
    - pip
    - ruamel.yaml
about:
  description: 'This package was split of from ruamel.yaml, so that ruamel.yaml can
    be build as a universal wheel.

    Apart from the C code seldom changing, and taking a long time to compile for all
    platforms, this allows

    installation of the .so on Linux systems under /usr/lib64/pythonX.Y (without a
    .pth file or a ruamel

    directory) and the Python code for ruamel.yaml under /usr/lib/pythonX.Y.

    '
  dev_url: https://sourceforge.net/projects/ruamel-yaml-clib/
  doc_source_url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.6/tree/_doc/
  doc_url: https://yaml.readthedocs.io
  home: https://sourceforge.net/projects/ruamel-yaml-clib/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  license_url: https://sourceforge.net/p/ruamel-yaml-clib/code/ci/0.2.6/tree/LICENSE
  summary: C version of reader, parser and emitter for ruamel.yaml derived from libyaml
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: aa4af63b-a1e0-4573-b868-0fd77b346fe5
  recipe-maintainers:
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/ruamel.yaml.clib-feedstock.git
  sha: c1bb1b3cc6bc8adcbecf071e4ac5ae362c96c534
