# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# /Users/ktietz/demo/src/aggregate/gast-feedstock/recipe, last modified Tue Aug 10 11:47:59 2021
# ------------------------------------------------

package:
  name: gast
  version: 0.4.0
source:
  fn: gast-0.4.0.tar.gz
  sha256: 40feb7b8b8434785585ab224d1568b857edb18297e5a3047f1ba012bc83b42c1
  url: https://pypi.io/packages/source/g/gast/gast-0.4.0.tar.gz
build:
  noarch: python
  number: '0'
  script: /Users/ktietz/demo/mc3/conda-bld/gast_1628588903283/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placeh/bin/python
    -m pip install . --no-deps -vv
  string: pyhd3eb1b0_0
requirements:
  host:
    - ca-certificates 2021.4.13 hca03da5_1
    - certifi 2021.5.30 py39hca03da5_0
    - expat 2.4.1 hc377ac9_2
    - libcxx 12.0.0 hf6beb65_1
    - libffi 3.3 hc4ed4cf_2
    - libiconv 1.16 h1230e6a_0
    - ncurses 6.2 hc4ed4cf_0
    - openssl 1.1.1j h1230e6a_0
    - pip 21.2.2 py39hca03da5_0
    - python 3.9.6 hc8d96b9_3
    - readline 8.1 h1230e6a_0
    - setuptools 52.0.0 py39hca03da5_0
    - sqlite 3.35.4 h9835d80_0
    - tk 8.6.10 h6b60437_0
    - tzdata 2021a h5d7bf9c_0
    - wheel 0.36.2 pyhd3eb1b0_0
    - xz 5.2.4 h1230e6a_0
    - zlib 1.2.11 hca03da5_3
  run:
    - python
test:
  imports:
    - gast
about:
  description: 'GAST provides a compatibility layer between the AST of various Python

    versions, as produced by ast.parse from the standard ast module.

    '
  dev_url: https://github.com/serge-sans-paille/gast
  home: https://github.com/serge-sans-paille/gast
  license: BSD-3-Clause
  license_family: BSD
  license_file: /Users/ktietz/demo/src/aggregate/gast-feedstock/recipe/LICENSE
  summary: A generic AST to represent Python2 and Python3's Abstract Syntax Tree(AST).
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - CurtLH
    - martinRenou
