# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\tf\aggregate\tensorflow_recipes\tensorboard-plugin-wit, last modified Thu Aug  4 07:37:04 2022
# ------------------------------------------------

package:
  name: tensorboard-plugin-wit
  version: 1.8.1
source:
  sha256: ff26bdd583d155aa951ee3b152b3d0cffae8005dc697f72b44a8e8c2a77a8cbe
  url: https://pypi.io/packages/py3/t/tensorboard-plugin-wit/tensorboard_plugin_wit-1.8.1-py3-none-any.whl
build:
  number: '0'
  script:
    - python -m pip install --no-deps --ignore-installed ./tensorboard_plugin_wit-1.8.1-py3-none-any.whl
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.6.15 py38haa95532_0
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.1.2 py38haa95532_0
    - python 3.8.13 h6244533_0
    - setuptools 61.2.0 py38haa95532_0
    - sqlite 3.39.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
    - setuptools
    - wheel >=0.26
test:
  imports:
    - tensorboard_plugin_wit
about:
  dev_url: https://github.com/PAIR-code/what-if-tool
  doc_url: https://pair-code.github.io/what-if-tool/learn/
  home: https://pair-code.github.io/what-if-tool/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: What-If Tool TensorBoard plugin
extra:
  copy_test_source_files: true
  final: true
