# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_d3cv5rzljl\clone\recipe, last modified Thu Jun 15 19:08:04 2023
# ------------------------------------------------

package:
  name: absl-py
  version: 1.4.0
source:
  sha256: d2c244d01048ba476e7c080bd2c6df5e141d211de80223460d5b3b8a2a58433d
  url: https://pypi.io/packages/source/a/absl-py/absl-py-1.4.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_d3cv5rzljl\\croot\\absl-py_1686852506854\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2023.05.30 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.8 h2bbff1b_0
    - pip 23.1.2 py38haa95532_0
    - python 3.8.16 h1aa4202_4
    - setuptools 67.8.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  imports:
    - absl
    - absl.flags
    - absl.logging
    - absl.testing
  requires:
    - pip
about:
  description: 'This repository is a collection of Python library code for building
    Python applications.

    The code is collected from Google''s own Python code base,

    and has been extensively tested and used in production.

    '
  dev_url: https://github.com/abseil/abseil-py
  doc_url: https://abseil.io/docs/python/
  home: https://abseil.io/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Abseil Common Libraries (Python)
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: d3283554-8d34-4a1d-8d2d-75a4a7ddc85c
  recipe-maintainers:
    - jjhelmus
  remote_url: git@github.com:AnacondaRecipes/absl-py-feedstock.git
  sha: e68ab666db36d1f6c8ce0697c758317f31c5408b
