# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_98lv_ucina\clone\recipe, last modified Tue Dec 20 13:11:47 2022
# ------------------------------------------------

package:
  name: markdown
  version: 3.4.1
source:
  sha256: 3b809086bb6efad416156e00a0da66fe47618a5d6918dd688f53f40c8e4cfeff
  url: https://pypi.io/packages/source/M/Markdown/Markdown-3.4.1.tar.gz
build:
  entry_points:
    - markdown_py = markdown.__main__:run
  number: '0'
  script: C:\b\abs_98lv_ucina\croot\markdown_1671541919225\_h_env\python.exe -m pip
    install . --no-deps --ignore-installed -vvv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.10.11 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.3.1 py38haa95532_0
    - python 3.8.15 h6244533_2
    - setuptools 65.5.0 py38haa95532_0
    - sqlite 3.40.0 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - importlib-metadata >=4.4
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
    - markdown_py -h
  imports:
    - markdown
    - markdown.extensions
  requires:
    - pip
about:
  description: "This is a Python implementation of John Gruber\u2019s Markdown. It\
    \ is almost\ncompletely compliant with the reference implementation, though there\
    \ are a\nfew very minor differences.\n"
  dev_url: https://github.com/Python-Markdown/markdown
  doc_url: https://python-markdown.github.io/
  home: https://github.com/Python-Markdown/markdown
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Python implementation of Markdown.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 98fba1ea-e79e-4e60-bbf0-23a1227ac0f3
  recipe-maintainers:
    - djsutherland
    - philip-khor
  remote_url: git@github.com:AnacondaRecipes/markdown-feedstock.git
  sha: a61ad9c28df756f51c83449430418ab215a16761
