# This file created by conda-build 3.23.3
# meta.yaml template originally from:
# C:\b\abs_513qafmfzk\clone\recipe, last modified Wed Feb  1 20:01:26 2023
# ------------------------------------------------

package:
  name: protobuf
  version: 3.20.3
source:
  sha256: 9c0fd39c7a08dff543c643f0f4baf081988129a411b977a07c46221793605638
  url: https://github.com/protocolbuffers/protobuf/archive/v3.20.3/protobuf-v3.20.3.tar.gz
build:
  number: '0'
  string: py38hd77b12b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.01.10 haa95532_0
    - certifi 2022.12.7 py38haa95532_0
    - libffi 3.4.2 hd77b12b_6
    - libprotobuf 3.20.3 h23ce68f_0
    - openssl 1.1.1s h2bbff1b_0
    - pip 22.3.1 py38haa95532_0
    - python 3.8.16 h6244533_2
    - setuptools 65.6.3 py38haa95532_0
    - sqlite 3.40.1 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
    - zlib 1.2.13 h8cc25b3_0
  run:
    - libprotobuf 3.20.3.*
    - libprotobuf >=3.20.3,<3.21.0a0
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - python -c "from google.protobuf.internal import api_implementation; assert api_implementation.Type()
      == 'python'"
  imports:
    - google
    - google.protobuf
    - google.protobuf.compiler
    - google.protobuf.internal
    - google.protobuf.pyext
    - google.protobuf.util
  requires:
    - pip
about:
  description: 'Protocol buffers are Google''s language-neutral, platform-neutral,
    extensible

    mechanism for serializing structured data,think XML, but smaller, faster, and
    simpler.

    '
  dev_url: https://github.com/protocolbuffers/protobuf
  doc_url: https://developers.google.com/protocol-buffers/docs/tutorials
  home: https://developers.google.com/protocol-buffers/
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Protocol Buffers - Google's data interchange format.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 5170457a-8ada-46bf-bf27-686ed7ab6460
  recipe-maintainers:
    - dopplershift
    - hajapy
    - jakirkham
    - ocefpaf
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/protobuf-feedstock.git
  sha: 54310c61fecfabbc17b51b3bd53cd997c7c2686a
