# This file created by conda-build 3.28.2
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Jan  8 15:15:57 2024
# ------------------------------------------------

package:
  name: jupyter_core
  version: 5.7.1
source:
  sha256: de61a9d7fc71240f688b2fb5ab659fbb56979458dc66a71decd098e03c79e218
  url: https://github.com/jupyter/jupyter_core/releases/download/v5.7.1/jupyter_core-5.7.1.tar.gz
build:
  entry_points:
    - jupyter = jupyter_core.command:main
    - jupyter-migrate = jupyter_core.migrate:main
    - jupyter-troubleshoot = jupyter_core.troubleshoot:main
  number: '0'
  script: D:\\bld\\jupyter_core_1704727211067\\_h_env\\python.exe -m pip install .
    --no-deps -vv
  string: py38haa244fe_0
requirements:
  build: []
  host:
    - bzip2 1.0.8 hcfcfb64_5
    - ca-certificates 2023.11.17 h56e8100_0
    - editables 0.3 pyhd8ed1ab_0
    - hatchling 1.21.0 pyhd8ed1ab_0
    - importlib-metadata 7.0.1 pyha770c72_0
    - libffi 3.4.2 h8ffe710_5
    - libsqlite 3.44.2 hcfcfb64_0
    - libzlib 1.2.13 hcfcfb64_5
    - openssl 3.2.0 hcfcfb64_1
    - packaging 23.2 pyhd8ed1ab_0
    - pathspec 0.12.1 pyhd8ed1ab_0
    - pip 23.3.2 pyhd8ed1ab_0
    - pluggy 1.3.0 pyhd8ed1ab_0
    - python 3.8.18 h4de0772_1_cpython
    - setuptools 69.0.3 pyhd8ed1ab_0
    - tk 8.6.13 h5226925_1
    - tomli 2.0.1 pyhd8ed1ab_0
    - trove-classifiers 2023.11.29 pyhd8ed1ab_0
    - ucrt 10.0.22621.0 h57928b3_0
    - vc 14.3 hcf57466_18
    - vc14_runtime 14.38.33130 h82b7239_18
    - vs2015_runtime 14.38.33130 hcb4865c_18
    - wheel 0.42.0 pyhd8ed1ab_0
    - xz 5.2.6 h8d14728_0
    - zipp 3.17.0 pyhd8ed1ab_0
  run:
    - platformdirs >=2.5
    - python >=3.8,<3.9.0a0
    - python_abi 3.8.* *_cp38
    - pywin32 >=300
    - traitlets >=5.3
test:
  commands:
    - pip check
    - jupyter -h
    - jupyter-migrate -h
    - jupyter-troubleshoot --help
    - pytest -vv --color=yes  -k "not (test_not_on_path or test_path_priority)"
  downstreams:
    - nbconvert-core
  imports:
    - jupyter_core
  requires:
    - pip
    - pytest-cov
  source_files:
    - tests
about:
  dev_url: https://github.com/jupyter/jupyter_core
  doc_source_url: https://github.com/jupyter/jupyter_core/tree/v5.7.1/docs
  doc_url: https://jupyter-core.readthedocs.io
  home: https://jupyter.org
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Core common functionality of Jupyter projects.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: azure_20240108.4.1
  recipe-maintainers:
    - Carreau
    - SylvainCorlay
    - blink1073
    - bollwyvl
    - jakirkham
    - jasongrout
    - minrk
    - ocefpaf
    - pelson
  remote_url: https://github.com/conda-forge/jupyter_core-feedstock
  sha: babd8161a908949db92ef9c2d3713719f44148e1
