CI: azure
c_compiler: vs2017
channel_sources: conda-forge
channel_targets: conda-forge main
cl_version: 19.38.33130
cpu_optimization_target: nocona
cran_mirror: https://cran.r-project.org
cross_target_platform: win-64
cxx_compiler: vs2017
extend_keys:
- ignore_build_only_deps
- extend_keys
- ignore_version
- pin_run_as_build
fortran_compiler: gfortran
ignore_build_only_deps:
- python
- numpy
lua: '5'
numpy: '1.22'
perl: 5.26.2
pin_run_as_build:
  python:
    min_pin: x.x
    max_pin: x.x
  r-base:
    min_pin: x.x
    max_pin: x.x
python: '3.10'
r_base: '3.4'
runtime_version: 14.38.33130
sha256: 4DFE83C91124CD542F4222FE2C396CABEAC617BB6F59BDCBDF89FD6F0DF0A32F
target_platform: win-64
update_version: '8'
uuid: a061be25-c14a-489a-8c7c-bb72adfb3cab
vc: '14'
vcver: '14.3'
vsver: '17'
vsyear: '2022'
zip_keys:
- - vcver
  - vsyear
  - vsver
  - runtime_version
  - update_version
  - cl_version
  - uuid
  - sha256
  - cross_target_platform
