# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_a8nmng7d_x\clone\recipe, last modified Wed Sep 27 22:28:47 2023
# ------------------------------------------------

package:
  name: pooch
  version: 1.7.0
source:
  sha256: f174a1041b6447f0eef8860f76d17f60ed2f857dc0efa387a7f08228af05d998
  url: https://pypi.io/packages/source/p/pooch/pooch-1.7.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_a8nmng7d_x\\croot\\pooch_1695850149827\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.11 h2bbff1b_2
    - packaging 23.1 py38haa95532_0
    - pip 23.2.1 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - setuptools-scm 7.1.0 py38haa95532_0
    - setuptools_scm 7.1.0 hd3eb1b0_0
    - sqlite 3.41.2 h2bbff1b_0
    - tomli 2.0.1 py38haa95532_0
    - typing-extensions 4.7.1 py38haa95532_0
    - typing_extensions 4.7.1 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py38haa95532_0
  run:
    - packaging >=20.0
    - platformdirs >=2.5.0
    - python >=3.8,<3.9.0a0
    - requests >=2.19.0
  run_constrained:
    - paramiko >=2.7.0
    - tqdm >=4.41.0,<5.0.0
    - xxhash >=1.4.3
test:
  commands:
    - pytest --pyargs pooch.tests.test_integration
    - pip check
  imports:
    - pooch
  requires:
    - pip
    - pytest
about:
  description: 'Pooch manages your remote data files. It automatically downloads and
    stores

    them in a local directory (using HTTP or FTP), with support for versioning,

    corruption checks, and custom download and post-processing operations.

    '
  dev_url: https://github.com/fatiando/pooch
  doc_url: https://www.fatiando.org/pooch
  home: https://github.com/fatiando/pooch
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.txt
  summary: A friend to fetch your data files
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: a8a839df-56c8-4ca0-9a39-218e874d969b
  recipe-maintainers:
    - dopplershift
    - leouieda
  remote_url: git@github.com:AnacondaRecipes/pooch-feedstock.git
  sha: 09bd70cd8f2d7e0acc49234ff39b74859853ac49
