# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# /feedstock/recipe, last modified Fri Jul 28 21:01:46 2023
# ------------------------------------------------

package:
  name: python-tzdata
  version: '2023.3'
source:
  sha256: 11ef1e08e54acb0d4f95bdb1be05da659673de4acbd21bf9c69e94cc5e907a3a
  url: https://pypi.io/packages/source/t/tzdata/tzdata-2023.3.tar.gz
build:
  noarch: python
  number: '0'
  script: /croot/python-tzdata_1690578112552/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla/bin/python
    -m pip install . -vv --no-deps --no-build-isolation
  string: pyhd3eb1b0_0
requirements:
  host:
    - _libgcc_mutex 0.1 main
    - _openmp_mutex 5.1 1_gnu
    - bzip2 1.0.8 h7b6447c_0
    - ca-certificates 2023.05.30 h06a4308_0
    - ld_impl_linux-64 2.38 h1181459_1
    - libffi 3.4.4 h6a678d5_0
    - libgcc-ng 11.2.0 h1234567_1
    - libgomp 11.2.0 h1234567_1
    - libstdcxx-ng 11.2.0 h1234567_1
    - libuuid 1.41.5 h5eee18b_0
    - ncurses 6.4 h6a678d5_0
    - openssl 3.0.9 h7f8727e_0
    - pip 23.2.1 py311h06a4308_0
    - python 3.11.4 h955ad1f_0
    - readline 8.2 h5eee18b_0
    - setuptools 68.0.0 py311h06a4308_0
    - sqlite 3.41.2 h5eee18b_0
    - tk 8.6.12 h1ccaba5_0
    - tzdata 2023c h04d1e81_0
    - wheel 0.38.4 py311h06a4308_0
    - xz 5.4.2 h5eee18b_0
    - zlib 1.2.13 h5eee18b_0
  run:
    - python
test:
  commands:
    - pip check
  imports:
    - tzdata
  requires:
    - pip
about:
  description: 'This is a Python package containing zic-compiled binaries for the
    IANA time zone database.

    It is intended to be a fallback for systems that do not have system time zone
    data installed (or don''t have it installed in a standard location),

    as a part of PEP 615.

    '
  dev_url: https://github.com/python/tzdata
  doc_url: https://tzdata.readthedocs.io/
  home: https://github.com/python/tzdata
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Provider of IANA time zone data
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 7a304e47-aa4b-457e-95ec-65f0fd1d5352
  recipe-maintainers:
    - mbargull
    - ocefpaf
    - pganssle
  remote_url: git@github.com:AnacondaRecipes/python-tzdata-feedstock.git
  sha: 0643428da775da48caadbf80853bb5f7456d9508
  skip-lints:
    - avoid_noarch
