# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_1anqjntpan\clone\recipe, last modified Fri May 26 16:01:39 2023
# ------------------------------------------------

package:
  name: joblib
  version: 1.2.0
source:
  sha256: 574eca5aaeb0a06c4fe0a8e8e67b24715218fb0f9d0fdc9d4f30519100885e53
  url: https://github.com/joblib/joblib/archive/1.2.0.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_1anqjntpan\\croot\\joblib_1685113317150\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2023.01.10 haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py38haa95532_0
    - python 3.8.16 h6244533_3
    - setuptools 66.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
    - python -c "from joblib import Memory, Parallel, delayed"
  imports:
    - joblib
    - joblib.externals
    - joblib.externals.cloudpickle
    - joblib.externals.loky
    - joblib.externals.loky.backend
    - joblib.test
    - joblib.test.data
  requires:
    - pip
    - pytest
about:
  description: '"A set of tools to provide lightweight pipelining in Python. In particular:

    transparent disk-caching of functions and lazy re-evaluation (memoize pattern),

    easy simple parallel computing. Joblib is optimized to be fast and robust on

    large data in particular and has specific optimizations for numpy arrays."

    '
  dev_url: https://github.com/joblib/joblib
  doc_url: https://joblib.readthedocs.io/
  home: https://joblib.readthedocs.io/
  license: BSD-3-Clause
  license_family: BSD
  license_url: https://github.com/joblib/joblib/blob/1.2.0/LICENSE.txt
  summary: 'Lightweight pipelining: using Python functions as pipeline jobs.'
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1af149d5-e6c2-4458-9892-e48ce5405a01
  recipe-maintainers:
    - jakirkham
    - lesteve
    - ocefpaf
    - ogrisel
    - pierreglaser
    - tomMoral
  remote_url: git@github.com:AnacondaRecipes/joblib-feedstock.git
  sha: d5bd1834b06b6984c177d539f0482900852c9539
