# This file created by conda-build 3.26.1
# meta.yaml template originally from:
# C:\b\abs_f6l4yaiqsl\clone\recipe, last modified Fri Sep  1 14:32:59 2023
# ------------------------------------------------

package:
  name: libtiff
  version: 4.5.1
source:
  - folder: .
    sha256: d7f38b6788e4a8f5da7940c5ac9424f494d8a79eba53d555f4a507167dca5e2b
    url: https://download.osgeo.org/libtiff/tiff-4.5.1.tar.gz
build:
  missing_dso_whitelist:
    - /opt/X11/lib/libGL.1.dylib
    - /opt/X11/lib/libglut.3.dylib
  number: '0'
  run_exports:
    - libtiff >=4.5.1,<5.0a0
  string: hd77b12b_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.05.30 haa95532_0
    - cmake 3.26.4 h693b641_0
    - libffi 3.4.4 hd77b12b_0
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 3.0.10 h2bbff1b_2
    - python 3.11.4 he1021f5_0
    - sqlite 3.41.2 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.4.2 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.5 hd43e919_0
  host:
    - jpeg 9e h2bbff1b_1
    - lerc 3.0 hd77b12b_0
    - libdeflate 1.17 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  run:
    - jpeg >=9e,<10a
    - lerc >=3.0,<4.0a0
    - libdeflate >=1.17,<1.18.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - xz >=5.2.10,<6.0a0
    - xz >=5.2.4,<6.0a0
    - zlib >=1.2.13,<1.3.0a0
    - zstd >=1.5.2,<1.6.0a0
test:
  commands:
    - if not exist %PREFIX%\\Library\\bin\\tiff.dll exit 1
    - if not exist %PREFIX%\\Library\\lib\\tiffxx.lib exit 1
    - if not exist %PREFIX%\\Library\\bin\\libtiff.dll exit 1
  downstreams:
    - pillow >=8
    - py-opencv >=4
about:
  description: 'This software provides support for the Tag Image File Format (TIFF),
    a

    widely used format for storing image data.

    '
  dev_url: https://gitlab.com/libtiff/libtiff
  doc_url: http://www.simplesystems.org/libtiff/
  home: http://www.simplesystems.org/libtiff/
  license: HPND
  license_family: Other
  license_file: LICENSE.md
  summary: Support for the Tag Image File Format (TIFF).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f68417c4-7eb3-41f1-8322-7156b80f79da
  recipe-maintainers:
    - jakirkham
    - mingwandroid
    - msarahan
    - ocefpaf
    - stuarteberg
  remote_url: git@github.com:AnacondaRecipes/libtiff-feedstock.git
  sha: 8e0c7224fb793c033a990033156a4f29e7512842
