# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# D:\a\1\s\recipe, last modified Mon Oct 24 16:40:33 2022
# ------------------------------------------------

package:
  name: ucrt
  version: 10.0.22621.0
source:
  sha256: 0412fc77e364226c9395e3188a2d0ac5888317fecfba7bc2dbe003c2ddb5b3d3
  url: https://software-static.download.prss.microsoft.com/dbazure/888969d5-f34g-4e03-ac9d-1f9786c66749/22621.1.220506-1250.ni_release_WindowsSDK.iso
build:
  number: '0'
  string: h57928b3_0
requirements:
  build: []
  host: []
  run: []
  run_constrained:
    - vs2015_runtime >=14.29.30037
test:
  commands:
    - if not exist %PREFIX%\\ucrtbase.dll exit 1
    - if not exist %LIBRARY_PREFIX%\\bin\\ucrtbase.dll exit 1
about:
  home: https://developer.microsoft.com/en-us/windows/downloads/windows-10-sdk/
  license: LicenseRef-Proprietary
  license_file: LICENSE.txt
  summary: Redistributable files for Windows SDK. This is only needed Windows <10
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - isuruf
    - xhochy
