# This file created by conda-build 3.21.9
# meta.yaml template originally from:
# C:\Users\BUILDE~1\AppData\Local\Temp\abs_7f_7lba6rl\clone\recipe, last modified Thu Aug 25 18:35:32 2022
# ------------------------------------------------

package:
  name: pyparsing
  version: 3.0.9
source:
  sha256: 2b020ecf7d21b687f219b71ecad3631f644a47f01403fa1d1036b0c6416d70fb
  url: https://pypi.io/packages/source/p/pyparsing/pyparsing-3.0.9.tar.gz
build:
  number: '0'
  script: C:\\Users\\BUILDE~1\\AppData\\Local\\Temp\\abs_7f_7lba6rl\\croots\\recipe\\pyparsing_1661452540662\\_h_env\\python.exe
    -m pip install . -vv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.6.15 py38haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.1.2 py38haa95532_0
    - python 3.8.13 h6244533_0
    - setuptools 63.4.1 py38haa95532_0
    - sqlite 3.39.2 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  imports:
    - pyparsing
  requires:
    - pip
about:
  description: 'The pyparsing module is an alternative approach to creating and executing

    simple grammars, vs. the traditional lex/yacc approach, or the use of

    regular expressions. The pyparsing module provides a library of classes

    that client code uses to construct the grammar directly in Python code.

    '
  dev_url: https://github.com/pyparsing/pyparsing/
  doc_url: https://github.com/pyparsing/pyparsing/blob/master/docs/HowToUsePyparsing.rst
  home: https://github.com/pyparsing/pyparsing/
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Create and execute simple grammars
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 7f2bcb21-a996-45cd-bc64-6c74860aea83
  recipe-maintainers:
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/pyparsing-feedstock.git
  sha: db8ce6deff95a85a6711649b8bd41b19b82807c2
