# This file created by conda-build 3.21.4
# meta.yaml template originally from:
# C:\ci\containers\00003bdaof7\tmp\build\80754af9\rsync-recipes\openjpeg-2.4.0-on-winbuilder, last modified Fri Aug 27 14:47:17 2021
# ------------------------------------------------

package:
  name: openjpeg
  version: 2.4.0
source:
  sha256: 8702ba68b442657f11aaeb2b338443ca8d5fb95b0d845757968a7be31ef7f16d
  url: https://github.com/uclouvain/openjpeg/archive/v2.4.0.tar.gz
build:
  ignore_run_exports:
    - zlib
  number: '0'
  run_exports:
    - openjpeg >=2.4.0,<3.0a0
  string: h4fc8c34_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - cmake 3.19.6 h9ad04ae_0
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h62dcd97_4
    - zstd 1.4.9 h19a0ad4_0
  host:
    - jpeg 9b hb83a4c4_2
    - libpng 1.6.37 h2a8f88b_0
    - libtiff 4.1.0 h56a325e_1
    - lz4-c 1.9.3 h2bbff1b_1
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - xz 5.2.5 h62dcd97_0
    - zlib 1.2.11 h62dcd97_4
    - zstd 1.4.9 h19a0ad4_0
  run:
    - libpng >=1.6.37,<1.7.0a0
    - libtiff >=4.1.0,<5.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - opj_dump -i p0_01.j2k
  files:
    - p0_01.j2k
about:
  home: http://www.openjpeg.org/
  license: BSD 2-Clause
  license_file: LICENSE
  summary: An open-source JPEG 2000 codec written in C
extra:
  copy_test_source_files: true
  final: true
  recipe-maintainers:
    - gillins
    - mingwandroid
    - ocefpaf
