# This file created by conda-build 3.26.0
# meta.yaml template originally from:
# C:\b\abs_17fav01gwy\clone\recipe, last modified Wed Aug  9 15:01:49 2023
# ------------------------------------------------

package:
  name: h5py
  version: 3.9.0
source:
  sha256: ac46f5caae570c9312edea6f65ad4e894e8da44a868b7f263e15265bc3de7a16
  url: https://github.com/h5py/h5py/archive/3.9.0.tar.gz
build:
  number: '0'
  string: py38hfc34f40_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - blas 1.0 mkl
    - ca-certificates 2023.05.30 haa95532_0
    - cython 0.29.36 py38h2bbff1b_0
    - hdf5 1.12.1 h51c971a_3
    - icc_rt 2022.1.0 h6049295_2
    - intel-openmp 2023.1.0 h59b6b97_46319
    - libffi 3.4.4 hd77b12b_0
    - m2w64-libwinpthread-git 5.0.0.4634.697f757 2
    - m2w64-pkg-config 0.29.1 2
    - mkl 2023.1.0 h6b88ed4_46357
    - mkl-service 2.4.0 py38h2bbff1b_1
    - mkl_fft 1.3.6 py38hf11a4ad_1
    - mkl_random 1.2.2 py38hf11a4ad_1
    - msys2-conda-epoch 20160418 1
    - numpy 1.21.5 py38h6917f2d_4
    - numpy-base 1.21.5 py38h46c4fa8_4
    - openssl 3.0.10 h2bbff1b_0
    - pip 23.2.1 py38haa95532_0
    - pkgconfig 1.5.4 py38haa95532_0
    - python 3.8.17 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tbb 2021.8.0 h59b6b97_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
    - zlib 1.2.13 h8cc25b3_0
  run:
    - hdf5 >=1.12.1,<1.12.2.0a0
    - numpy >=1.21.5,<2.0a0
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - h5py
    - h5py.tests
    - h5py.tests.data_files
    - h5py.tests.test_vds
  requires:
    - curl
    - pip
    - pytest
    - pytest-mpi
about:
  description: Read and write HDF5 files from Python
  dev_url: https://github.com/h5py/h5py
  doc_url: https://docs.h5py.org/en/stable/
  home: https://www.h5py.org/
  license: BSD-3-Clause
  license_family: BSD
  license_file: licenses/license.txt
  summary: Read and write HDF5 files from Python
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 1743c70f-1828-4c63-ad3b-115efc404dad
  recipe-maintainers:
    - jakirkham
    - minrk
    - ocefpaf
    - scopatz
    - tacaswell
  remote_url: git@github.com:AnacondaRecipes/h5py-feedstock.git
  sha: f01808f1e84c4982d01652b50c8223fb112236b2
