# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_f0fz6xub77\clone\recipe, last modified Wed Oct 26 15:30:38 2022
# ------------------------------------------------

package:
  name: freetype
  version: 2.12.1
source:
  sha256: efe71fd4b8246f1b0b1b9bfca13cfff1c9ad85930340c27df469733bbb620938
  url: https://download.savannah.gnu.org/releases/freetype/freetype-2.12.1.tar.gz
build:
  number: '0'
  run_exports:
    - freetype >=2.12.1,<3.0a0
  string: ha860e81_0
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2022.07.19 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_4
    - libuv 1.40.0 he774522_0
    - lz4-c 1.9.3 h2bbff1b_1
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1q h2bbff1b_0
    - python 3.10.6 hbb2ffb3_1
    - sqlite 3.39.3 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2022e h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.6 h8cc25b3_0
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.2 h19a0ad4_0
  host:
    - libpng 1.6.37 h2a8f88b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_0
  run:
    - libpng >=1.6.37,<1.7.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - if exist %LIBRARY_BIN%\freetype.dll (exit 0) else (exit 1)
about:
  description: 'FreeType is designed to be small, efficient, highly customizable

    and portable while capable of producing high-quality output (glyph images)

    of most vector and bitmap font formats.

    '
  dev_url: https://gitlab.freedesktop.org/freetype/freetype
  doc_source_url: https://gitlab.freedesktop.org/freetype/freetype
  doc_url: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/README
  home: https://freetype.org/
  license: GPL-2-only and LicenseRef-FreeType
  license_family: Other
  license_file:
    - docs/FTL.TXT
    - docs/GPLv2.TXT
  license_url: https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/LICENSE.TXT
  summary: A Free, High-Quality, and Portable Font Engine
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: f0ca5e7e-3044-44c9-af6f-73c9061ab98d
  recipe-maintainers:
    - ccordoba12
    - msarahan
    - ocefpaf
  remote_url: git@github.com:AnacondaRecipes/freetype-feedstock.git
  sha: 7112aa3b6f409b1bde037cbc16f274ecfecfd533
