# This file created by conda-build 3.24.0
# meta.yaml template originally from:
# C:\b\abs_afm0oewmmt\clone\recipe, last modified Thu May  4 18:37:01 2023
# ------------------------------------------------

package:
  name: numexpr
  version: 2.8.4
source:
  sha256: d5432537418d18691b9115d615d6daa17ee8275baef3edf1afbbf8bc69806147
  url: https://pypi.io/packages/source/n/numexpr/numexpr-2.8.4.tar.gz
build:
  number: '1'
  script: C:\\b\\abs_afm0oewmmt\\croot\\numexpr_1683221839116\\_h_env\\python.exe
    -m pip install . --no-deps --no-build-isolation -vv
  string: py38h7b80656_1
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - blas 1.0 mkl
    - ca-certificates 2023.01.10 haa95532_0
    - icc_rt 2022.1.0 h6049295_2
    - intel-openmp 2023.1.0 h59b6b97_46319
    - libffi 3.4.2 hd77b12b_6
    - mkl 2023.1.0 h8bd8f75_46356
    - mkl-devel 2023.1.0 h74d85ca_46356
    - mkl-include 2023.1.0 haa95532_46356
    - mkl-service 2.4.0 py38h2bbff1b_1
    - mkl_fft 1.3.6 py38hf11a4ad_1
    - mkl_random 1.2.2 py38hf11a4ad_1
    - numpy 1.16.6 py38h749eb61_5
    - numpy-base 1.16.6 py38h9413944_5
    - openssl 1.1.1t h2bbff1b_0
    - pip 23.0.1 py38haa95532_0
    - python 3.8.16 h6244533_3
    - setuptools 66.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tbb 2021.8.0 h59b6b97_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.38.4 py38haa95532_0
  run:
    - blas 1.0 mkl
    - mkl >=2023.1.0,<2024.0a0
    - mkl-service >=2.3.0,<3.0a0
    - numpy >=1.16.6,<2.0a0
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
  imports:
    - numexpr
    - numexpr.interpreter
  requires:
    - pip
about:
  description: 'Numexpr is a fast numerical expression evaluator for NumPy. With it,

    expressions that operate on arrays (like "3*a+4*b") are accelerated and use

    less memory than doing the same calculation in Python.

    '
  dev_url: https://github.com/pydata/numexpr
  doc_url: https://github.com/pydata/numexpr/wiki/Numexpr-Users-Guide
  home: https://github.com/pydata/numexpr
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Fast numerical expression evaluator for NumPy.
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: af00e3d9-77e0-4de0-b421-607dd4dbfafa
  recipe-maintainers:
    - djkirkham
    - msarahan
    - ocefpaf
    - scopatz
  remote_url: git@github.com:AnacondaRecipes/numexpr-feedstock.git
  sha: 3f7e4d7e14bad2a9a4f77ebd6d456c0afa0125e3
