# This file created by conda-build 3.27.0
# meta.yaml template originally from:
# C:\b\abs_8bxwdyhjvp\clone\recipe, last modified Mon Nov 27 17:13:48 2023
# ------------------------------------------------

package:
  name: yarl
  version: 1.9.3
source:
  sha256: 4a14907b597ec55740f63e52d7fee0e9ee09d5b9d57a4f399a7423268e457b57
  url: https://pypi.io/packages/source/y/yarl/yarl-1.9.3.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_8bxwdyhjvp\\croot\\yarl_1701105248152\\_h_env\\python.exe -m
    pip install . --no-deps --no-build-isolation -vv
  string: py38h2bbff1b_0
requirements:
  build:
    - vs2017_win-64 19.16.27032.1 hb4161e2_3
    - vswhere 2.8.4 haa95532_0
  host:
    - ca-certificates 2023.08.22 haa95532_0
    - cython 3.0.0 py38h2bbff1b_0
    - expandvars 0.12.0 py38haa95532_0
    - libffi 3.4.4 hd77b12b_0
    - openssl 3.0.12 h2bbff1b_0
    - pip 23.3.1 py38haa95532_0
    - python 3.8.18 h1aa4202_0
    - setuptools 68.0.0 py38haa95532_0
    - sqlite 3.41.2 h2bbff1b_0
    - tomli 2.0.1 py38haa95532_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.41.2 py38haa95532_0
  run:
    - idna >=2.0
    - multidict >=4.0
    - python >=3.8,<3.9.0a0
    - vc >=14.1,<15.0a0
    - vs2015_runtime >=14.16.27012,<15.0a0
test:
  commands:
    - pip check
    - py.test tests
  imports:
    - yarl
  requires:
    - pip
    - pytest
  source_files:
    - tests
about:
  dev_url: https://github.com/aio-libs/yarl
  doc_url: https://yarl.aio-libs.org
  home: https://github.com/aio-libs/yarl
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Yet another URL library
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: 8b605b34-c97b-4d1c-aea1-0e8ac4e293f3
  recipe-maintainers:
    - sodre
  remote_url: git@github.com:AnacondaRecipes/yarl-feedstock.git
  sha: 5063d8f2198d0318b1506d442f612bbc057638dd
