# This file created by conda-build 3.24.0
# ------------------------------------------------

package:
  name: libclang13
  version: 14.0.6
source:
  - folder: llvm-project
    patches:
      - patches/0001-Find-conda-gcc-installation.patch
      - patches/0002-Fix-sysroot-detection-for-linux.patch
      - patches/0003-clang-add-conda-specific-env-var-CONDA_BUILD_SYSROOT.patch
      - patches/0004-Fix-normalizeProgramName-s-handling-of-dots-outside-.patch
      - patches/0005-Set-VERSION-in-osx-as-well.patch
      - patches/0006-Fix-crosscompiling-LLVM-tools.patch
      - patches/0008-set-libclang-SOVERSION-unconditionally.patch
      - patches/llvm_winpython.diff
    sha256: 8b3cfd7bc695bd6cea0f37f53f0981f34f87496e79e2529874fd03a2f9dd3a8a
    url: https://github.com/llvm/llvm-project/releases/download/llvmorg-14.0.6/llvm-project-14.0.6.src.tar.xz
build:
  number: 1
  run_exports:
    - libclang13 >=14.0.6,<14.1.0a0
  string: default_h8e68704_1
  track_features: null
requirements:
  build:
    - bzip2 1.0.8 he774522_0
    - ca-certificates 2023.01.10 haa95532_0
    - cmake 3.22.1 h9ad04ae_0
    - libffi 3.4.2 hd77b12b_6
    - libuv 1.44.2 h2bbff1b_0
    - lz4-c 1.9.4 h2bbff1b_0
    - ninja 1.10.2 haa95532_5
    - ninja-base 1.10.2 h6d14046_5
    - openssl 1.1.1t h2bbff1b_0
    - python 3.11.2 h966fe2a_0
    - sqlite 3.41.1 h2bbff1b_0
    - tk 8.6.12 h2bbff1b_0
    - tzdata 2023c h04d1e81_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - vs2019_win-64 19.27.29111 ha89c4d3_2
    - vswhere 2.8.4 haa95532_0
    - xz 5.2.10 h8cc25b3_1
    - zlib 1.2.13 h8cc25b3_0
    - zstd 1.5.4 hd43e919_0
  host:
    - clang 14.0.6 haa95532_1
    - libiconv 1.16 h2bbff1b_2
    - libllvm14 14.0.6 h4157e71_2
    - libxml2 2.10.3 h0ad7f3c_0
    - llvm 14.0.6 h2eaa2aa_2
    - llvm-tools 14.0.6 h4157e71_2
    - llvmdev 14.0.6 h4157e71_2
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - zlib 1.2.13 h8cc25b3_0
  run:
    - vc >=14.2,<15.0a0
    - vs2015_runtime >=14.27.29016,<15.0a0
    - zlib >=1.2.13,<1.3.0a0
test:
  commands:
    - if not exist %LIBRARY_BIN%\\libclang-13.dll exit 1
    - if exist %LIBRARY_BIN%\\libclang.dll exit 1
    - if exist %LIBRARY_LIB%\\libclang.lib exit 1
    - if exist %LIBRARY_BIN%\\libclang-14.dll exit 1
about:
  dev_url: https://github.com/llvm/llvm-project
  doc_url: https://llvm.org/docs/
  home: https://llvm.org/
  license: Apache-2.0 WITH LLVM-exception
  license_family: Apache
  license_file: clang/LICENSE.TXT
  summary: Development headers and libraries for Clang
extra:
  copy_test_source_files: true
  feedstock-name: clang
  final: true
  flow_run_id: 86ebdfa2-42dd-46a1-b285-4b3007d2352a
  recipe-maintainers:
    - SylvainCorlay
    - chrisburr
    - h-vetinari
    - inducer
    - isuruf
    - jakirkham
    - timsnyder
    - xhochy
  remote_url: git@github.com:AnacondaRecipes/clangdev-feedstock.git
  sha: 58b35d181c931ae29d40f363e8cec7f96c4fbf18
