# This file created by conda-build 3.22.0
# meta.yaml template originally from:
# C:\b\abs_bdhbebrioa\clone\recipe, last modified Tue Oct 18 20:39:25 2022
# ------------------------------------------------

package:
  name: idna
  version: '3.4'
source:
  sha256: 814f528e8dead7d329833b91c5faa87d60bf71824cd12a7530b5526063d02cb4
  url: https://pypi.io/packages/source/i/idna/idna-3.4.tar.gz
build:
  number: '0'
  script: C:\\b\\abs_bdhbebrioa\\croot\\idna_1666125572046\\_h_env\\python.exe -m
    pip install . -vvv
  string: py38haa95532_0
requirements:
  host:
    - ca-certificates 2022.07.19 haa95532_0
    - certifi 2022.9.24 py38haa95532_0
    - flit-core 3.6.0 pyhd3eb1b0_0
    - openssl 1.1.1q h2bbff1b_0
    - pip 22.2.2 py38haa95532_0
    - python 3.8.13 h6244533_0
    - setuptools 63.4.1 py38haa95532_0
    - sqlite 3.39.3 h2bbff1b_0
    - vc 14.2 h21ff451_1
    - vs2015_runtime 14.27.29016 h5e58377_2
    - wheel 0.37.1 pyhd3eb1b0_0
    - wincertstore 0.2 py38haa95532_2
  run:
    - python >=3.8,<3.9.0a0
test:
  commands:
    - pip check
  imports:
    - idna
    - idna.codec
    - idna.compat
  requires:
    - pip
about:
  description: 'A library to support the Internationalised Domain Names in Applications

    (IDNA) protocol as specified in RFC 5891. This version of the protocol

    is often referred to as "IDNA2008".

    '
  dev_url: https://github.com/kjd/idna
  doc_url: https://github.com/kjd/idna/blob/master/README.rst
  home: https://github.com/kjd/idna
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.md
  summary: Internationalized Domain Names in Applications (IDNA).
extra:
  copy_test_source_files: true
  final: true
  flow_run_id: bd934d52-4e41-4235-b0ce-8c5a8e9bcecc
  recipe-maintainers:
    - goanpeca
    - jschueller
  remote_url: git@github.com:AnacondaRecipes/idna-feedstock.git
  sha: e08109603646ed4a27e09a78107f0c8166543787
